/****************************************************************************
**
** Metadata for CS_MJPG_CONTROLLib generated by dumpcpp from type library
** c:\csr\Exe\mjpegControl\32\CS_MJPG_Control.dll
**
****************************************************************************/

#define QAX_DUMPCPP_CS_MJPG_CONTROLLIB_NOINLINES
#include "./Cs_MJPG_Ctrl.h"

using namespace CS_MJPG_CONTROLLib;

static const uint qt_meta_data_CS_MJPG_CONTROLLib__CS_MjpgCtrl[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       12,    14, // methods
       5,    74, // properties
       1,    89, // enums/sets

 // classinfo: key, value
       32, 50, 
       70, 82, 

 // signals: signature, parameters, type, tag, flags
       95, 115, 128, 129, 5,
       130, 169, 191, 192, 5,
       193, 218, 223, 224, 5,
       225, 251, 266, 267, 5,

 // slots: signature, parameters, type, tag, flags
       268, 275, 276, 277, 9,
       278, 297, 307, 308, 9,
       309, 327, 337, 338, 9,
       339, 359, 370, 371, 9,
       372, 393, 402, 403, 9,
       404, 426, 439, 440, 9,
       441, 448, 449, 450, 9,
       451, 476, 489, 490, 9,

 // properties: name, type, flags
       491, 501, 0x01015003, 		 // bool AutoStart
       506, 516, 0x02015003, 		 // int FrameRate
       520, 531, 0x01015003, 		 // bool KeepAspect
       536, 545, 0x0a015003, 		 // QString MediaURL
       553, 566, 0x01015003, 		 // bool StretchToFit

 // enums: name, flags, count, data
       571, 0x0, 2, 93, 

 // enum data: key, value
       588, CS_MJPG_CONTROLLib::CS_EVST_DISCONNECTED,
       609, CS_MJPG_CONTROLLib::CS_EVST_CONNECTED,

        0        // eod
};

static const char qt_meta_enumstringdata_CS_MJPG_CONTROLLib[] = {
    "cs_enu_HttpState\0"
    "CS_EVST_DISCONNECTED\0CS_EVST_CONNECTED\0"

};

static const char *qt_meta_stringdata_CS_MJPG_CONTROLLib__CS_MjpgCtrl() {
    static const char stringdata0[] = {
    "CS_MJPG_CONTROLLib::CS_MjpgCtrl\0"
    "Event Interface 1\0_ICS_MjpgCtrlEvents\0Interface 0\0ICS_MjpgCtrl\0"
    "OnStatusChange(int)\0theNewStatus\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0"
    "name,argc,argv\0\0\0"
    "Play()\0\0\0\0SetAutoStart(bool)\0AutoStart\0\0\0SetFrameRate(int)\0FrameRate\0\0\0SetKeepAspect(bool)\0KeepAspect\0\0\0SetMediaURL(QString)\0MediaURL\0\0\0SetStretchToFit(bool)\0StretchToFit\0\0\0Stop()\0\0\0\0setLogLevel(QString,int)\0"
    "logger,level\0\0\0"
    "AutoStart\0bool\0FrameRate\0int\0KeepAspect\0bool\0MediaURL\0QString\0StretchToFit\0bool\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_CS_MJPG_CONTROLLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_CS_MJPG_CONTROLLib, sizeof(qt_meta_enumstringdata_CS_MJPG_CONTROLLib));
    }

    return data;
};

const QMetaObject CS_MjpgCtrl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_CS_MJPG_CONTROLLib__CS_MjpgCtrl(),
qt_meta_data_CS_MJPG_CONTROLLib__CS_MjpgCtrl }
};

void *CS_MjpgCtrl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_CS_MJPG_CONTROLLib__CS_MjpgCtrl()))
        return static_cast<void*>(const_cast<CS_MjpgCtrl*>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_CS_MJPG_CONTROLLib__ICS_MjpgCtrl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       11,    10, // methods
       6,    65, // properties
       1,    83, // enums/sets

 // signals: signature, parameters, type, tag, flags
       33, 72, 94, 95, 5,
       96, 121, 126, 127, 5,
       128, 154, 169, 170, 5,

 // slots: signature, parameters, type, tag, flags
       171, 178, 179, 180, 9,
       181, 200, 210, 211, 9,
       212, 230, 240, 241, 9,
       242, 262, 273, 274, 9,
       275, 296, 305, 306, 9,
       307, 329, 342, 343, 9,
       344, 351, 352, 353, 9,
       354, 379, 392, 393, 9,

 // properties: name, type, flags
       394, 404, 0x01015003, 		 // bool AutoStart
       409, 419, 0x02015003, 		 // int FrameRate
       423, 434, 0x01015003, 		 // bool KeepAspect
       439, 448, 0x0a015003, 		 // QString MediaURL
       456, 469, 0x01015003, 		 // bool StretchToFit
       474, 482, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
       490, 0x0, 2, 87, 

 // enum data: key, value
       507, CS_MJPG_CONTROLLib::CS_EVST_DISCONNECTED,
       528, CS_MJPG_CONTROLLib::CS_EVST_CONNECTED,

        0        // eod
};

static const char *qt_meta_stringdata_CS_MJPG_CONTROLLib__ICS_MjpgCtrl() {
    static const char stringdata0[] = {
    "CS_MJPG_CONTROLLib::ICS_MjpgCtrl\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Play()\0\0\0\0SetAutoStart(bool)\0AutoStart\0\0\0SetFrameRate(int)\0FrameRate\0"
    "\0\0SetKeepAspect(bool)\0KeepAspect\0\0\0SetMediaURL(QString)\0MediaURL\0\0\0SetStretchToFit(bool)\0StretchToFit\0\0\0Stop()\0\0\0\0setLogLevel(QString,int)\0logger,level\0\0\0"
    "AutoStart\0bool\0FrameRate\0int\0KeepAspect\0bool\0MediaURL\0"
    "QString\0StretchToFit\0bool\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_CS_MJPG_CONTROLLib)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_CS_MJPG_CONTROLLib, sizeof(qt_meta_enumstringdata_CS_MJPG_CONTROLLib));
    }

    return data;
};

const QMetaObject ICS_MjpgCtrl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_CS_MJPG_CONTROLLib__ICS_MjpgCtrl(),
qt_meta_data_CS_MJPG_CONTROLLib__ICS_MjpgCtrl }
};

void *ICS_MjpgCtrl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_CS_MJPG_CONTROLLib__ICS_MjpgCtrl()))
        return static_cast<void*>(const_cast<ICS_MjpgCtrl*>(this));
    return QAxObject::qt_metacast(_clname);
}

