/****************************************************************************
**
** Namespace CS_MJPG_CONTROLLib generated by dumpcpp from type library
** c:\csr\Exe\mjpegControl\32\CS_MJPG_Control.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_CS_MJPG_CTRL_H
#define QAX_DUMPCPP_CS_MJPG_CTRL_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef CS_MJPG_CONTROLLIB_EXPORT
#define CS_MJPG_CONTROLLIB_EXPORT
#endif

#include <QAxObject>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace CS_MJPG_CONTROLLib {

    enum cs_enu_HttpState {
        CS_EVST_DISCONNECTED    = 0,
        CS_EVST_CONNECTED       = 1
    };

// forward declarations
    enum cs_enu_HttpState;
    enum cs_enu_HttpState;

// skipping event interface _ICS_MjpgCtrlEvents

class CS_MJPG_CONTROLLIB_EXPORT ICS_MjpgCtrl : public QAxObject
{
public:
    ICS_MjpgCtrl(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property AutoStart

    indicates if the media stream is to be played automatically

    */
    inline bool AutoStart() const; //Returns the value of AutoStart
    inline void SetAutoStart(bool value); //Sets the value of the AutoStart property

    /*
    Property FrameRate

    max frameRate

    */
    inline int FrameRate() const; //Returns the value of FrameRate
    inline void SetFrameRate(int value); //Sets the value of the FrameRate property

    /*
    Property KeepAspect

    True to keep original picture aspect

    */
    inline bool KeepAspect() const; //Returns the value of KeepAspect
    inline void SetKeepAspect(bool value); //Sets the value of the KeepAspect property

    /*
    Property MediaURL

    URL where the media stream can be accessed

    */
    inline QString MediaURL() const; //Returns the value of MediaURL
    inline void SetMediaURL(const QString& value); //Sets the value of the MediaURL property

    /*
    Property StretchToFit

    true if stretched to fit the control frame size

    */
    inline bool StretchToFit() const; //Returns the value of StretchToFit
    inline void SetStretchToFit(bool value); //Sets the value of the StretchToFit property

    /*
    Method Play

    start playing a media stream

    */
    inline void Play();

    /*
    Method Stop

    stop playing a media stream

    */
    inline void Stop();

    /*
    Method setLogLevel

    method setLogLevel

    */
    inline void setLogLevel(const QString& logger, int level);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class CS_MJPG_CONTROLLIB_EXPORT CS_MjpgCtrl : public QAxWidget
{
public:
    CS_MjpgCtrl(QWidget *parent = 0, Qt::WindowFlags f = (Qt::WindowFlags)0)
    : QAxWidget(parent, f)
    {
        setControl("{592f8fca-57a5-4fc7-8273-3fa504b64a10}");
    }

    CS_MjpgCtrl(ICS_MjpgCtrl *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property AutoStart

    indicates if the media stream is to be played automatically

    */
    inline bool AutoStart() const; //Returns the value of AutoStart
    inline void SetAutoStart(bool value); //Sets the value of the AutoStart property

    /*
    Property FrameRate

    max frameRate

    */
    inline int FrameRate() const; //Returns the value of FrameRate
    inline void SetFrameRate(int value); //Sets the value of the FrameRate property

    /*
    Property KeepAspect

    True to keep original picture aspect

    */
    inline bool KeepAspect() const; //Returns the value of KeepAspect
    inline void SetKeepAspect(bool value); //Sets the value of the KeepAspect property

    /*
    Property MediaURL

    URL where the media stream can be accessed

    */
    inline QString MediaURL() const; //Returns the value of MediaURL
    inline void SetMediaURL(const QString& value); //Sets the value of the MediaURL property

    /*
    Property StretchToFit

    true if stretched to fit the control frame size

    */
    inline bool StretchToFit() const; //Returns the value of StretchToFit
    inline void SetStretchToFit(bool value); //Sets the value of the StretchToFit property

    /*
    Method Play

    start playing a media stream

    */
    inline void Play();

    /*
    Method Stop

    stop playing a media stream

    */
    inline void Stop();

    /*
    Method setLogLevel

    method setLogLevel

    */
    inline void setLogLevel(const QString& logger, int level);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_CS_MJPG_CONTROLLIB_NOINLINES
inline bool CS_MjpgCtrl::AutoStart() const
{
    QVariant qax_result = property("AutoStart");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void CS_MjpgCtrl::SetAutoStart(bool value){ setProperty("AutoStart", QVariant(value)); }

inline int CS_MjpgCtrl::FrameRate() const
{
    QVariant qax_result = property("FrameRate");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void CS_MjpgCtrl::SetFrameRate(int value){ setProperty("FrameRate", QVariant(value)); }

inline bool CS_MjpgCtrl::KeepAspect() const
{
    QVariant qax_result = property("KeepAspect");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void CS_MjpgCtrl::SetKeepAspect(bool value){ setProperty("KeepAspect", QVariant(value)); }

inline QString CS_MjpgCtrl::MediaURL() const
{
    QVariant qax_result = property("MediaURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void CS_MjpgCtrl::SetMediaURL(const QString& value){ setProperty("MediaURL", QVariant(value)); }

inline bool CS_MjpgCtrl::StretchToFit() const
{
    QVariant qax_result = property("StretchToFit");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void CS_MjpgCtrl::SetStretchToFit(bool value){ setProperty("StretchToFit", QVariant(value)); }

inline void CS_MjpgCtrl::Play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
}

inline void CS_MjpgCtrl::Stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
}

inline void CS_MjpgCtrl::setLogLevel(const QString& logger, int level)
{
    void *_a[] = {0, (void*)&logger, (void*)&level};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
}


inline bool ICS_MjpgCtrl::AutoStart() const
{
    QVariant qax_result = property("AutoStart");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ICS_MjpgCtrl::SetAutoStart(bool value){ setProperty("AutoStart", QVariant(value)); }

inline int ICS_MjpgCtrl::FrameRate() const
{
    QVariant qax_result = property("FrameRate");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void ICS_MjpgCtrl::SetFrameRate(int value){ setProperty("FrameRate", QVariant(value)); }

inline bool ICS_MjpgCtrl::KeepAspect() const
{
    QVariant qax_result = property("KeepAspect");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ICS_MjpgCtrl::SetKeepAspect(bool value){ setProperty("KeepAspect", QVariant(value)); }

inline QString ICS_MjpgCtrl::MediaURL() const
{
    QVariant qax_result = property("MediaURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ICS_MjpgCtrl::SetMediaURL(const QString& value){ setProperty("MediaURL", QVariant(value)); }

inline bool ICS_MjpgCtrl::StretchToFit() const
{
    QVariant qax_result = property("StretchToFit");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ICS_MjpgCtrl::SetStretchToFit(bool value){ setProperty("StretchToFit", QVariant(value)); }

inline void ICS_MjpgCtrl::Play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
}

inline void ICS_MjpgCtrl::Stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void ICS_MjpgCtrl::setLogLevel(const QString& logger, int level)
{
    void *_a[] = {0, (void*)&logger, (void*)&level};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}



#endif

}

template<>
inline void *qMetaTypeConstructHelper(const CS_MJPG_CONTROLLib::CS_MjpgCtrl *t)
{ Q_ASSERT(!t); return new CS_MJPG_CONTROLLib::CS_MjpgCtrl; }

template<>
inline void *qMetaTypeConstructHelper(const CS_MJPG_CONTROLLib::ICS_MjpgCtrl *t)
{ Q_ASSERT(!t); return new CS_MJPG_CONTROLLib::ICS_MjpgCtrl; }

#endif

