#define _PROP_SERVICE			"SERVICE"
#define _PROP_TYPE				"TYPE"
#define _PROP_PROJECT			"PROJECT"
#define _PROP_VERSION			"VERSION"
#define _PROP_LANGUAGE			"LANGUAGE"
#define _PROP_TYPE_OF_LANE		"TYPE_OF_LANE"
#define _PROP_TYPE_OF_SHIFT		"TYPE_OF_SHIFT"
#define _PROP_MAIN_DLG_HIDDEN	"MAIN_DLG_HIDDEN"
#define _PROP_OBJECT			"OBJECT"
#define _PROP_VALUE				"VALUE"
#define _PROP_TOOLTIP			"TOOLTIP"

#define _PROP_PROPERTY			"PROPERTY"
#define _PROP_MANUAL_LOGIN		"MANUAL_LOGIN"
#define _PROP_LDAP_OFFLINE		"LDAP_OFFLINE"
#define _PROP_VISIBLITY			"VISIBILITY"
#define _PROP_GROUPE			"GROUPE"
#define _PROP_ASCII				"ASCII"
#define _PROP_ETAT				"ETAT"
#define _PROP_DEFINITION		"DEFINITION"
#define _PROP_SAISIE			"SAISIE"
#define _PROP_COUPLE_ID			"COUPLE_ID"
#define _PROP_PREPOSTAMBULES	"PREPOSTAMBULES"
#define _PROP_DLG_NAME			"DIALOG_NAME"
#define _PROP_DLG_TYPE			"DIALOG_TYPE"
#define _PROP_NO_CONTROLS		"NO_OF_CONTROLS"
#define _PROP_CTRL_STRING		"CONTROLS_STRING"
#define _PROP_FILENAME			"FILENAME"
#define _PROP_BUTTONS			"BUTTONS"
#define _PROP_VIDEO				"VIDEO"
#define _PROP_SOURCE			"SOURCE"
#define _PROP_COMMAND			"COMMAND"
#define _PROP_USER				"USER"
#define _PROP_PASSWORD			"PASSWORD"
#define _PROP_IS_CODE_PWD		"IS_CODE_PWD"
#define _PROP_SESSION			"SESSION"
#define _PROP_DESKTOP			"DESKTOP"
#define _PROP_IS_FILE			"IS_FILE"
#define _PROP_DIALOG_ID			"DIALOG_ID"
#define _PROP_DO_NOT_RELOAD		"DO_NOT_RELOAD"

#define _PROP_VAL_DEBUT			"DEBUT"
#define _PROP_VAL_FIN			"FIN"
#define _PROP_VAL_DEMANDE		"DEMANDE"
#define _PROP_VAL_EFFECTUE		"EFFECTUE"
#define _PROP_VAL_ANULATE		"ANNULATION"
#define _PROP_VAL_SET			"SET"
#define _PROP_VAL_GET			"GET"
#define _PROP_VAL_ICON			"ICON"
#define _PROP_VAL_LABEL			"LABEL"
#define _PROP_VAL_OBJECT		"OBJECT"
#define _PROP_VAL_VIDEO			"VIDEO"
#define _PROP_VAL_IMAGE			"IMAGE"


enum
{
	ARRET = 0,
	AFF_DEBUT_ACQ,
	AFF_DEBUT_NACQ,
	AFF_FIN_ACQ,
	AFF_FIN_NACQ,
	AFF_SET_ACQ,
	AFF_SET_NACQ,
	CONF_SET_ACQ,
	CONF_SET_NACQ,
	CONF_GET_ACQ,
	CONF_GET_NACQ,
	CONF_CONF_ACTUELE,
	TOUC_DEMANDE,
	TOUC_DEMANDE_ACQ,
	TOUC_DEMANDE_NACQ,
	TOUC_NOUVELLE,
	DETC_DEBUT_ACQ,
	DETC_DEBUT_NACQ,
	DETC_FIN_ACQ,
	DETC_FIN_NACQ,
	DETC_NOUVELLE_CHAINE
};

#define SIMU_NOM_BAL				"IHM_REPONSE_"
#define SIMU_NOM_IHM_INST_DEFAULT	"BL_IHM_PEAGER"
#define SIMU_CONF_FILE				"ihm_simu_conf.xml"
#define SIMU_CONF_FILE_ROOT_TAG		"IHM_SIMU_config"
#define SIMU_ACT_SCRIPT_ROOT_TAG	"IHM_SIMU_script"

#define XML_AFFICHAGE				"AFFICHAGE"
#define XML_CONFIG					"CONFIG"
#define XML_TOUCHE					"TOUCHES"
#define XML_ACTION					"ACTION"
#define XML_VIDEO					"VIDEO"
#define XML_AUTHORIZATION			"AUTHORIZATION"



