; ********** GENERAL CMDSVC TEST TOOL SETTINGS *********

[GENERAL_SETTINGS]
DefaultLanguage=English
LanguageFilePath=./CMDSVC/csr_CmdSvc_Tool_Languages.xml
StylesheetPath=./CMDSVC/csr_CmdSvc_Style.css
DialogStylesheetPath=./CMDSVC/csr_CmdSvc_Dialog_Style.css
TraceAndErrorFileNamePrefix=csr_CMDSVC_Tool
AboutDialogLogoPath=":/Images/EmovisLogo.png"
TraceFileEnabled=true
ErrorFileEnabled=true
TracePath=../_traces
ErrorPath=../_errors
FileMaxSize=1
FormatPath=C:/csr/exe
;If WindowSize is blank, 0x0 or some invalid value, default value will be used!
WindowSize=
;If WindowPosition is blank or some invalid value, default value will be used! Position format: x.y
WindowPosition=
WindowIconPath=:/Images/CmdSvc_Tool.png
WorkMode=Test
InstanceName="MAINWND_LBL_INSTANCE_NAME1"

; *********** Language picker SETTINGS **********
; *********** Language picker SETTINGS **********

[APP_LANGUAGE_IDS]
Language0=English
;Language1=French
Language2=Croatian

[English]
STATE_SELECTING_IMG = ":/Images/EN.png"
STATE_SELECTED_IMG = ":/Images/EN2.png"
LANG_SHORT_LABEL = "ENG"

[French]
STATE_SELECTING_IMG = ":/Images/FR.png"
STATE_SELECTED_IMG = ":/Images/FR2.png"
LANG_SHORT_LABEL = "FRA"

[Croatian]
STATE_SELECTING_IMG = ":/Images/HR.png"
STATE_SELECTED_IMG = ":/Images/HR2.png"
LANG_SHORT_LABEL = "HRV"

