<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>
        ".\INCLUDES";
        ".\SOURCES";
        ".\RESOURCES";
        "L:\Commun_nt\DECLARE\10.0.0";
        "L:\Commun_nt\LIST\10.0.0";
        "L:\Commun_nt\REG\10.0.2";
        "L:\Commun_nt\SRV\10.0.0";
        "L:\Commun_nt\TRC\10.0.3";
        "L:\Voie_nt\AFF\11.0.x";
        "L:\Voie_nt\AFF\_aff_util\11.0.0";
        "L:\Voie_nt\COMMUN\3.3.0";
        "L:\Voie_nt\CONVERT\10.0.0";
        "L:\Voie_nt\FIC_GERE\10.1.2";
        "L:\Voie_nt\FONCT_C\11.0.1";
        "L:\Voie_nt\HRD\10.1.1";
        "L:\Voie_nt\MSG_FIC\10.1.1";
        "L:\Voie_nt\NOY\10.0.4";
        "L:\Voie_nt\RUN\10.0.2";
        "L:\Voie_nt\SER\10.0.2";
      </AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>