echo off

echo. >MESSAGES.MC

echo MessageIdTypedef = DWORD >>MESSAGES.MC
echo LanguageNames=(Neutral=0x0000:MSG00000) >>MESSAGES.MC
echo FacilityNames=(Generic=0) >>MESSAGES.MC
echo. >>MESSAGES.MC
ECHO MessageId=0 >>MESSAGES.MC
ECHO Severity=Success >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO SymbolicName=EVTLOG_MSG_SUCCESS >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=0 >>MESSAGES.MC
ECHO Severity=Informational >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO SymbolicName=EVTLOG_MSG_INFO >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=0 >>MESSAGES.MC
ECHO Severity=Warning >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO SymbolicName=EVTLOG_MSG_WARNING >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=0 >>MESSAGES.MC
ECHO Severity=Error >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO SymbolicName=EVTLOG_MSG_ERROR >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC

FOR /L %%i in (1,1,255) do call :ADDITEM %%i

GOTO EOF

:ADDITEM
ECHO %1
ECHO. >>MESSAGES.MC
ECHO MessageId=%1 >>MESSAGES.MC
ECHO Severity=Success >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=%1 >>MESSAGES.MC
ECHO Severity=Informational >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=%1 >>MESSAGES.MC
ECHO Severity=Warning >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC
ECHO MessageId=%1 >>MESSAGES.MC
ECHO Severity=Error >>MESSAGES.MC
ECHO Facility=Generic >>MESSAGES.MC
ECHO Language=Neutral >>MESSAGES.MC
ECHO %%1 >>MESSAGES.MC
ECHO .>>MESSAGES.MC
ECHO. >>MESSAGES.MC

:EOF
