<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile />
    <ClCompile>
      <AdditionalIncludeDirectories>
        ".\INCLUDES";
        "L:\Voie_NT\Rfr\11.0.0";
        "L:\COMMUN_NT\DECLARE\10.0.0";
        "L:\COMMUN_NT\REG\10.0.2";
        "L:\VOIE_NT\COMMUN\3.3.0";
        "L:\VOIE_NT\NOY\10.0.4";
        "L:\VOIE_NT\HRD\10.1.1";
        "L:\VOIE_NT\RUN\10.0.2";
        "L:\VOIE_NT\LAN\10.0.x";
        "L:\VOIE_NT\Fonct_C\11.0.1";
        "L:\VOIE_NT\Fic_gere\10.1.1";
        "L:\VOIE_NT\Fic_conf\10.1.1";
        "L:\Commun_NT\files_tools\10.2.0";
        "L:\Commun_NT\TRC\10.0.3";
      </AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>