
#include "template_handler.h"

const QString TemplateHandler::platformTemplate = 
	"<?php\n"
	"/*\n"
	"This file is automatically generated by the web config tool.\n"
	"*/\n"
	"define('IHM_SERVER_PORT', '%1');\n"
	"define('ACTIVE_LANE_NAME', '%2');\n";

QString TemplateHandler::BuildIHMWebPlatformConfig(StringPairs params)
{
	QString returnValue = QString(TemplateHandler::platformTemplate)
			.arg(params["--desktop-port"])
			.arg(params["--active-lane"]);

	return returnValue;
}

StringPairs TemplateHandler::BuildIHMWebDesktopConfig(StringPairs params)
{
	StringPairs	returnValue;

	returnValue["WebServerPort"] = params["--desktop-port"];

	return returnValue;
}
