/****************************************************************************
**
** Metadata for AXISMEDIACONTROLLib generated by dumpcpp from type library
** C:\Program Files\Axis Communications\AXIS Media Control Embedded\AxisMediaControlEmb.dll
**
****************************************************************************/

#define QAX_DUMPCPP_AXISMEDIACONTROLLIB_NOINLINES
#include "./sources/AxAxis.h"

using namespace AXISMEDIACONTROLLib;

static const uint qt_meta_data_AXISMEDIACONTROLLib__AxisMediaControl[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       82,    14, // methods
       49,    424, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       38, 56, 
       81, 93, 

 // signals: signature, parameters, type, tag, flags
       111, 128, 132, 133, 5,
       134, 165, 191, 192, 5,
       193, 214, 240, 241, 5,
       242, 257, 265, 266, 5,
       267, 280, 288, 289, 5,
       290, 319, 345, 346, 5,
       347, 376, 402, 403, 5,
       404, 431, 457, 458, 5,
       459, 489, 513, 514, 5,
       515, 528, 529, 530, 5,
       531, 555, 581, 582, 5,
       583, 633, 692, 693, 5,
       694, 733, 755, 756, 5,
       757, 782, 787, 788, 5,
       789, 815, 830, 831, 5,

 // slots: signature, parameters, type, tag, flags
       832, 852, 853, 854, 9,
       855, 874, 875, 876, 9,
       877, 898, 899, 900, 9,
       901, 921, 922, 923, 9,
       924, 960, 994, 995, 9,
       996, 1015, 1021, 1022, 9,
       1023, 1063, 1099, 1100, 9,
       1101, 1129, 1151, 1155, 9,
       1156, 1163, 1164, 1165, 9,
       1166, 1188, 1194, 1195, 9,
       1196, 1226, 1244, 1245, 9,
       1246, 1273, 1288, 1289, 9,
       1290, 1312, 1322, 1323, 9,
       1324, 1352, 1368, 1369, 9,
       1370, 1397, 1415, 1416, 9,
       1417, 1446, 1463, 1464, 9,
       1465, 1493, 1513, 1514, 9,
       1515, 1534, 1544, 1545, 9,
       1546, 1567, 1579, 1580, 9,
       1581, 1605, 1620, 1621, 9,
       1622, 1643, 1656, 1657, 9,
       1658, 1689, 1708, 1709, 9,
       1710, 1748, 1774, 1775, 9,
       1776, 1798, 1812, 1813, 9,
       1814, 1838, 1854, 1855, 9,
       1856, 1881, 1897, 1898, 9,
       1899, 1923, 1938, 1939, 9,
       1940, 1967, 1985, 1986, 9,
       1987, 2011, 2026, 2027, 9,
       2028, 2053, 2069, 2070, 9,
       2071, 2095, 2111, 2112, 9,
       2113, 2133, 2144, 2145, 9,
       2146, 2176, 2198, 2199, 9,
       2200, 2226, 2244, 2245, 9,
       2246, 2271, 2288, 2289, 9,
       2290, 2321, 2344, 2345, 9,
       2346, 2377, 2400, 2401, 9,
       2402, 2429, 2448, 2449, 9,
       2450, 2472, 2482, 2483, 9,
       2484, 2510, 2524, 2525, 9,
       2526, 2548, 2558, 2559, 9,
       2560, 2581, 2590, 2591, 9,
       2592, 2618, 2632, 2633, 9,
       2634, 2662, 2678, 2679, 9,
       2680, 2706, 2720, 2721, 9,
       2722, 2736, 2741, 2742, 9,
       2743, 2766, 2781, 2782, 9,
       2783, 2805, 2818, 2819, 9,
       2820, 2846, 2860, 2861, 9,
       2862, 2877, 2884, 2885, 9,
       2886, 2940, 3061, 3062, 9,
       3063, 3086, 3100, 3101, 9,
       3102, 3123, 3135, 3136, 9,
       3137, 3159, 3172, 3173, 9,
       3174, 3197, 3208, 3209, 9,
       3210, 3243, 3264, 3265, 9,
       3266, 3285, 3292, 3293, 9,
       3294, 3349, 3427, 3428, 9,
       3429, 3444, 3451, 3452, 9,
       3453, 3474, 3482, 3483, 9,
       3484, 3522, 3553, 3554, 9,
       3555, 3587, 3604, 3605, 9,
       3606, 3613, 3614, 3615, 9,
       3616, 3629, 3630, 3631, 9,
       3632, 3650, 3651, 3652, 9,
       3653, 3673, 3674, 3675, 9,
       3676, 3690, 3691, 3692, 9,

 // properties: name, type, flags
       3693, 3708, 0x0a015003, 		 // QString AudioConfigURL
       3716, 3726, 0x0a015003, 		 // QString AudioFile
       3734, 3750, 0x0a015003, 		 // QString AudioReceiveURL
       3758, 3776, 0x01015003, 		 // bool AudioTransmitMute
       3781, 3798, 0x0a015003, 		 // QString AudioTransmitURL
       3806, 3826, 0x02015003, 		 // int AudioTransmitVolume
       3830, 3840, 0x01015003, 		 // bool AutoStart
       3845, 3857, 0x03015003, 		 // uint ButtonColor
       3862, 3877, 0x01015003, 		 // bool ClarifyEnabled
       3882, 3895, 0x02015003, 		 // int ClarifyLevel
       3899, 3918, 0x0a015003, 		 // QString ClarifyLicenseFile
       3926, 3952, 0x0a015003, 		 // QString ClarifyValidatorsLocation
       3960, 3974, 0x02015003, 		 // int ClientOverlay
       3978, 3994, 0x02015003, 		 // int CurrentPosition
       3998, 4014, 0x01015003, 		 // bool DisplayMessages
       4019, 4028, 0x02005001, 		 // int Duration
       4032, 4047, 0x01015003, 		 // bool EnableAreaZoom
       4052, 4070, 0x01015003, 		 // bool EnableContextMenu
       4075, 4090, 0x01015003, 		 // bool EnableJoystick
       4095, 4111, 0x01015003, 		 // bool EnableReconnect
       4116, 4132, 0x02015003, 		 // int EnableRecording
       4136, 4148, 0x02005001, 		 // int FramesDrawn
       4152, 4163, 0x01015003, 		 // bool FullScreen
       4168, 4190, 0x02015003, 		 // int H264VideoDecodingMode
       4194, 4212, 0x02015003, 		 // int H264VideoRenderer
       4216, 4234, 0x01005001, 		 // bool JoystickConnected
       4239, 4262, 0x02015003, 		 // int MPEG2VideoDecodingMode
       4266, 4289, 0x02015003, 		 // int MPEG4VideoDecodingMode
       4293, 4312, 0x02015003, 		 // int MPEG4VideoRenderer
       4316, 4326, 0x0a015003, 		 // QString MediaFile
       4334, 4348, 0x0a015003, 		 // QString MediaPassword
       4356, 4366, 0x0a015003, 		 // QString MediaType
       4374, 4383, 0x0a015003, 		 // QString MediaURL
       4391, 4405, 0x0a015003, 		 // QString MediaUsername
       4413, 4429, 0x0a015003, 		 // QString MotionConfigURL
       4437, 4451, 0x0a015003, 		 // QString MotionDataURL
       4459, 4464, 0x01015003, 		 // bool Mute
       4469, 4484, 0x02015003, 		 // int NetworkTimeout
       4488, 4501, 0x01015003, 		 // bool OneClickZoom
       4506, 4520, 0x0a015003, 		 // QString PTZControlURL
       4528, 4535, 0x02015003, 		 // int Popups
       4539, 4553, 0x01015003, 		 // bool ShowStatusBar
       4558, 4570, 0x01015003, 		 // bool ShowToolbar
       4575, 4582, 0x02005001, 		 // int Status
       4586, 4599, 0x01015003, 		 // bool StretchToFit
       4604, 4615, 0x0a015003, 		 // QString SvgDataUrl
       4623, 4644, 0x0a015003, 		 // QString ToolbarConfiguration
       4652, 4659, 0x0a015003, 		 // QString UIMode
       4667, 4674, 0x02015003, 		 // int Volume

        0        // eod
};

static const char *qt_meta_stringdata_AXISMEDIACONTROLLib__AxisMediaControl() {
    static const char stringdata0[] = {
    "AXISMEDIACONTROLLib::AxisMediaControl\0"
    "Event Interface 1\0_IAxisMediaControlEvents\0Interface 0\0IAxisMediaControl\0"
    "OnClick(int,int)\0X,Y\0\0\0OnDoubleClick(int,int,int,int)\0nButton,nShiftState,fX,fY\0\0\0OnError(int,QString)\0theErrorCode,theErrorInfo\0"
    "\0\0OnJoyDown(int)\0nButton\0\0\0OnJoyUp(int)\0nButton\0\0\0OnMouseDown(int,int,int,int)\0nButton,nShiftState,fX,fY\0\0\0OnMouseMove(int,int,int,int)\0nButton,nShiftState,fX,fY\0\0\0OnMouseUp(int,int,int,int)\0nButton,nShiftState,fX,fY\0"
    "\0\0OnMouseWheel(int,int,int,int)\0nShiftState,Delta,fX,fY\0\0\0OnNewImage()\0\0\0\0OnStatusChange(int,int)\0theNewStatus,theOldStatus\0\0\0OnUserWindowChanged(int,int,int,int,int,int,bool)\0theID,theXPos,theYPos,theWidth,theHeight,theState,isForced\0"
    "\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AudioReceiveStart()\0\0\0\0AudioReceiveStop()\0\0\0\0AudioTransmitStart()\0"
    "\0\0\0AudioTransmitStop()\0\0\0\0GetCurrentImage(int,QVariant&,int&)\0theFormat,theBuffer,theBufferSize\0\0\0GetUserWindow(int)\0theID\0\0\0GetVersion(QString,int&,int&,int&,int&)\0theClsId,major,minor,build,revision\0"
    "\0\0GetVersionPart(QString,int)\0theClsId,thePartIndex\0int\0\0Play()\0\0\0\0RemoveUserWindow(int)\0theID\0\0\0SaveCurrentImage(int,QString)\0theFormat,theFile\0\0\0SetAudioConfigURL(QString)\0AudioConfigURL\0\0\0SetAudioFile(QString)\0"
    "AudioFile\0\0\0SetAudioReceiveURL(QString)\0AudioReceiveURL\0\0\0SetAudioTransmitMute(bool)\0AudioTransmitMute\0\0\0SetAudioTransmitURL(QString)\0AudioTransmitURL\0\0\0SetAudioTransmitVolume(int)\0AudioTransmitVolume\0"
    "\0\0SetAutoStart(bool)\0AutoStart\0\0\0SetButtonColor(uint)\0ButtonColor\0\0\0SetClarifyEnabled(bool)\0ClarifyEnabled\0\0\0SetClarifyLevel(int)\0ClarifyLevel\0\0\0SetClarifyLicenseFile(QString)\0ClarifyLicenseFile\0\0\0SetClarifyValidatorsLocation(QString)\0"
    "ClarifyValidatorsLocation\0\0\0SetClientOverlay(int)\0ClientOverlay\0\0\0SetCurrentPosition(int)\0CurrentPosition\0\0\0SetDisplayMessages(bool)\0DisplayMessages\0\0\0SetEnableAreaZoom(bool)\0EnableAreaZoom\0\0\0SetEnableContextMenu(bool)\0"
    "EnableContextMenu\0\0\0SetEnableJoystick(bool)\0EnableJoystick\0\0\0SetEnableReconnect(bool)\0EnableReconnect\0\0\0SetEnableRecording(int)\0EnableRecording\0\0\0SetFullScreen(bool)\0FullScreen\0\0\0SetH264VideoDecodingMode(int)\0"
    "H264VideoDecodingMode\0\0\0SetH264VideoRenderer(int)\0H264VideoRenderer\0\0\0SetImage(QVariant&,int&)\0theImage,theSize\0\0\0SetMPEG2VideoDecodingMode(int)\0MPEG2VideoDecodingMode\0\0\0SetMPEG4VideoDecodingMode(int)\0"
    "MPEG4VideoDecodingMode\0\0\0SetMPEG4VideoRenderer(int)\0MPEG4VideoRenderer\0\0\0SetMediaFile(QString)\0MediaFile\0\0\0SetMediaPassword(QString)\0MediaPassword\0\0\0SetMediaType(QString)\0MediaType\0\0\0SetMediaURL(QString)\0"
    "MediaURL\0\0\0SetMediaUsername(QString)\0MediaUsername\0\0\0SetMotionConfigURL(QString)\0MotionConfigURL\0\0\0SetMotionDataURL(QString)\0MotionDataURL\0\0\0SetMute(bool)\0Mute\0\0\0SetNetworkTimeout(int)\0NetworkTimeout\0\0"
    "\0SetOneClickZoom(bool)\0OneClickZoom\0\0\0SetPTZControlURL(QString)\0PTZControlURL\0\0\0SetPopups(int)\0Popups\0\0\0SetReconnectionStrategy(int,int,int,int,int,int,bool)\0theDuration1,theConnectionInterval1,theDuration2,theConnectionInterval2,theDuration3,theConnectionInterval3,infiniteMode\0"
    "\0\0SetShowStatusBar(bool)\0ShowStatusBar\0\0\0SetShowToolbar(bool)\0ShowToolbar\0\0\0SetStretchToFit(bool)\0StretchToFit\0\0\0SetSvgDataUrl(QString)\0SvgDataUrl\0\0\0SetToolbarConfiguration(QString)\0ToolbarConfiguration\0"
    "\0\0SetUIMode(QString)\0UIMode\0\0\0SetUserWindow(int,QString,int,int,int,int,int,int,int)\0theID,theName,theXPos,theYPos,theWidth,theHeight,theColor,theOpacity,theFlags\0\0\0SetVolume(int)\0Volume\0\0\0StartRecord(QString)\0"
    "theFile\0\0\0StartRecordMedia(QString,int,QString)\0theFile,theFlags,theMediaTypes\0\0\0StartTransmitMedia(QString,int)\0theFile,theFlags\0\0\0Stop()\0\0\0\0StopRecord()\0\0\0\0StopRecordMedia()\0\0\0\0StopTransmitMedia()\0\0\0"
    "\0TogglePause()\0\0\0\0"
    "AudioConfigURL\0QString\0AudioFile\0QString\0AudioReceiveURL\0QString\0AudioTransmitMute\0bool\0AudioTransmitURL\0QString\0AudioTransmitVolume\0int\0AutoStart\0bool\0ButtonColor\0uint\0ClarifyEnabled\0"
    "bool\0ClarifyLevel\0int\0ClarifyLicenseFile\0QString\0ClarifyValidatorsLocation\0QString\0ClientOverlay\0int\0CurrentPosition\0int\0DisplayMessages\0bool\0Duration\0int\0EnableAreaZoom\0bool\0EnableContextMenu\0bool\0EnableJoystick\0"
    "bool\0EnableReconnect\0bool\0EnableRecording\0int\0FramesDrawn\0int\0FullScreen\0bool\0H264VideoDecodingMode\0int\0H264VideoRenderer\0int\0JoystickConnected\0bool\0MPEG2VideoDecodingMode\0int\0MPEG4VideoDecodingMode\0int\0"
    "MPEG4VideoRenderer\0int\0MediaFile\0QString\0MediaPassword\0QString\0MediaType\0QString\0MediaURL\0QString\0MediaUsername\0QString\0MotionConfigURL\0QString\0MotionDataURL\0QString\0Mute\0bool\0NetworkTimeout\0int\0OneClickZoom\0"
    "bool\0PTZControlURL\0QString\0Popups\0int\0ShowStatusBar\0bool\0ShowToolbar\0bool\0Status\0int\0StretchToFit\0bool\0SvgDataUrl\0QString\0ToolbarConfiguration\0QString\0UIMode\0QString\0Volume\0int\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject AxisMediaControl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_AXISMEDIACONTROLLib__AxisMediaControl(),
qt_meta_data_AXISMEDIACONTROLLib__AxisMediaControl }
};

void *AxisMediaControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXISMEDIACONTROLLib__AxisMediaControl()))
        return static_cast<void*>(const_cast<AxisMediaControl*>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_AXISMEDIACONTROLLib__IAxisMediaControl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       70,    10, // methods
       50,    360, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       39, 78, 100, 101, 5,
       102, 127, 132, 133, 5,
       134, 160, 175, 176, 5,

 // slots: signature, parameters, type, tag, flags
       177, 197, 198, 199, 9,
       200, 219, 220, 221, 9,
       222, 243, 244, 245, 9,
       246, 266, 267, 268, 9,
       269, 305, 339, 340, 9,
       341, 360, 366, 367, 9,
       368, 408, 444, 445, 9,
       446, 474, 496, 500, 9,
       501, 508, 509, 510, 9,
       511, 533, 539, 540, 9,
       541, 571, 589, 590, 9,
       591, 618, 633, 634, 9,
       635, 657, 667, 668, 9,
       669, 697, 713, 714, 9,
       715, 742, 760, 761, 9,
       762, 791, 808, 809, 9,
       810, 838, 858, 859, 9,
       860, 879, 889, 890, 9,
       891, 912, 924, 925, 9,
       926, 950, 965, 966, 9,
       967, 988, 1001, 1002, 9,
       1003, 1034, 1053, 1054, 9,
       1055, 1093, 1119, 1120, 9,
       1121, 1143, 1157, 1158, 9,
       1159, 1183, 1199, 1200, 9,
       1201, 1226, 1242, 1243, 9,
       1244, 1268, 1283, 1284, 9,
       1285, 1312, 1330, 1331, 9,
       1332, 1356, 1371, 1372, 9,
       1373, 1398, 1414, 1415, 9,
       1416, 1440, 1456, 1457, 9,
       1458, 1478, 1489, 1490, 9,
       1491, 1521, 1543, 1544, 9,
       1545, 1571, 1589, 1590, 9,
       1591, 1616, 1633, 1634, 9,
       1635, 1666, 1689, 1690, 9,
       1691, 1722, 1745, 1746, 9,
       1747, 1774, 1793, 1794, 9,
       1795, 1817, 1827, 1828, 9,
       1829, 1855, 1869, 1870, 9,
       1871, 1893, 1903, 1904, 9,
       1905, 1926, 1935, 1936, 9,
       1937, 1963, 1977, 1978, 9,
       1979, 2007, 2023, 2024, 9,
       2025, 2051, 2065, 2066, 9,
       2067, 2081, 2086, 2087, 9,
       2088, 2111, 2126, 2127, 9,
       2128, 2150, 2163, 2164, 9,
       2165, 2191, 2205, 2206, 9,
       2207, 2222, 2229, 2230, 9,
       2231, 2285, 2406, 2407, 9,
       2408, 2431, 2445, 2446, 9,
       2447, 2468, 2480, 2481, 9,
       2482, 2504, 2517, 2518, 9,
       2519, 2542, 2553, 2554, 9,
       2555, 2588, 2609, 2610, 9,
       2611, 2630, 2637, 2638, 9,
       2639, 2694, 2772, 2773, 9,
       2774, 2789, 2796, 2797, 9,
       2798, 2819, 2827, 2828, 9,
       2829, 2867, 2898, 2899, 9,
       2900, 2932, 2949, 2950, 9,
       2951, 2958, 2959, 2960, 9,
       2961, 2974, 2975, 2976, 9,
       2977, 2995, 2996, 2997, 9,
       2998, 3018, 3019, 3020, 9,
       3021, 3035, 3036, 3037, 9,

 // properties: name, type, flags
       3038, 3053, 0x0a015003, 		 // QString AudioConfigURL
       3061, 3071, 0x0a015003, 		 // QString AudioFile
       3079, 3095, 0x0a015003, 		 // QString AudioReceiveURL
       3103, 3121, 0x01015003, 		 // bool AudioTransmitMute
       3126, 3143, 0x0a015003, 		 // QString AudioTransmitURL
       3151, 3171, 0x02015003, 		 // int AudioTransmitVolume
       3175, 3185, 0x01015003, 		 // bool AutoStart
       3190, 3202, 0x03015003, 		 // uint ButtonColor
       3207, 3222, 0x01015003, 		 // bool ClarifyEnabled
       3227, 3240, 0x02015003, 		 // int ClarifyLevel
       3244, 3263, 0x0a015003, 		 // QString ClarifyLicenseFile
       3271, 3297, 0x0a015003, 		 // QString ClarifyValidatorsLocation
       3305, 3319, 0x02015003, 		 // int ClientOverlay
       3323, 3339, 0x02015003, 		 // int CurrentPosition
       3343, 3359, 0x01015003, 		 // bool DisplayMessages
       3364, 3373, 0x02005001, 		 // int Duration
       3377, 3392, 0x01015003, 		 // bool EnableAreaZoom
       3397, 3415, 0x01015003, 		 // bool EnableContextMenu
       3420, 3435, 0x01015003, 		 // bool EnableJoystick
       3440, 3456, 0x01015003, 		 // bool EnableReconnect
       3461, 3477, 0x02015003, 		 // int EnableRecording
       3481, 3493, 0x02005001, 		 // int FramesDrawn
       3497, 3508, 0x01015003, 		 // bool FullScreen
       3513, 3535, 0x02015003, 		 // int H264VideoDecodingMode
       3539, 3557, 0x02015003, 		 // int H264VideoRenderer
       3561, 3579, 0x01005001, 		 // bool JoystickConnected
       3584, 3607, 0x02015003, 		 // int MPEG2VideoDecodingMode
       3611, 3634, 0x02015003, 		 // int MPEG4VideoDecodingMode
       3638, 3657, 0x02015003, 		 // int MPEG4VideoRenderer
       3661, 3671, 0x0a015003, 		 // QString MediaFile
       3679, 3693, 0x0a015003, 		 // QString MediaPassword
       3701, 3711, 0x0a015003, 		 // QString MediaType
       3719, 3728, 0x0a015003, 		 // QString MediaURL
       3736, 3750, 0x0a015003, 		 // QString MediaUsername
       3758, 3774, 0x0a015003, 		 // QString MotionConfigURL
       3782, 3796, 0x0a015003, 		 // QString MotionDataURL
       3804, 3809, 0x01015003, 		 // bool Mute
       3814, 3829, 0x02015003, 		 // int NetworkTimeout
       3833, 3846, 0x01015003, 		 // bool OneClickZoom
       3851, 3865, 0x0a015003, 		 // QString PTZControlURL
       3873, 3880, 0x02015003, 		 // int Popups
       3884, 3898, 0x01015003, 		 // bool ShowStatusBar
       3903, 3915, 0x01015003, 		 // bool ShowToolbar
       3920, 3927, 0x02005001, 		 // int Status
       3931, 3944, 0x01015003, 		 // bool StretchToFit
       3949, 3960, 0x0a015003, 		 // QString SvgDataUrl
       3968, 3989, 0x0a015003, 		 // QString ToolbarConfiguration
       3997, 4004, 0x0a015003, 		 // QString UIMode
       4012, 4019, 0x02015003, 		 // int Volume
       4023, 4031, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_AXISMEDIACONTROLLib__IAxisMediaControl() {
    static const char stringdata0[] = {
    "AXISMEDIACONTROLLib::IAxisMediaControl\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AudioReceiveStart()\0\0\0\0AudioReceiveStop()\0\0\0\0AudioTransmitStart()\0"
    "\0\0\0AudioTransmitStop()\0\0\0\0GetCurrentImage(int,QVariant&,int&)\0theFormat,theBuffer,theBufferSize\0\0\0GetUserWindow(int)\0theID\0\0\0GetVersion(QString,int&,int&,int&,int&)\0theClsId,major,minor,build,revision\0"
    "\0\0GetVersionPart(QString,int)\0theClsId,thePartIndex\0int\0\0Play()\0\0\0\0RemoveUserWindow(int)\0theID\0\0\0SaveCurrentImage(int,QString)\0theFormat,theFile\0\0\0SetAudioConfigURL(QString)\0AudioConfigURL\0\0\0SetAudioFile(QString)\0"
    "AudioFile\0\0\0SetAudioReceiveURL(QString)\0AudioReceiveURL\0\0\0SetAudioTransmitMute(bool)\0AudioTransmitMute\0\0\0SetAudioTransmitURL(QString)\0AudioTransmitURL\0\0\0SetAudioTransmitVolume(int)\0AudioTransmitVolume\0"
    "\0\0SetAutoStart(bool)\0AutoStart\0\0\0SetButtonColor(uint)\0ButtonColor\0\0\0SetClarifyEnabled(bool)\0ClarifyEnabled\0\0\0SetClarifyLevel(int)\0ClarifyLevel\0\0\0SetClarifyLicenseFile(QString)\0ClarifyLicenseFile\0\0\0SetClarifyValidatorsLocation(QString)\0"
    "ClarifyValidatorsLocation\0\0\0SetClientOverlay(int)\0ClientOverlay\0\0\0SetCurrentPosition(int)\0CurrentPosition\0\0\0SetDisplayMessages(bool)\0DisplayMessages\0\0\0SetEnableAreaZoom(bool)\0EnableAreaZoom\0\0\0SetEnableContextMenu(bool)\0"
    "EnableContextMenu\0\0\0SetEnableJoystick(bool)\0EnableJoystick\0\0\0SetEnableReconnect(bool)\0EnableReconnect\0\0\0SetEnableRecording(int)\0EnableRecording\0\0\0SetFullScreen(bool)\0FullScreen\0\0\0SetH264VideoDecodingMode(int)\0"
    "H264VideoDecodingMode\0\0\0SetH264VideoRenderer(int)\0H264VideoRenderer\0\0\0SetImage(QVariant&,int&)\0theImage,theSize\0\0\0SetMPEG2VideoDecodingMode(int)\0MPEG2VideoDecodingMode\0\0\0SetMPEG4VideoDecodingMode(int)\0"
    "MPEG4VideoDecodingMode\0\0\0SetMPEG4VideoRenderer(int)\0MPEG4VideoRenderer\0\0\0SetMediaFile(QString)\0MediaFile\0\0\0SetMediaPassword(QString)\0MediaPassword\0\0\0SetMediaType(QString)\0MediaType\0\0\0SetMediaURL(QString)\0"
    "MediaURL\0\0\0SetMediaUsername(QString)\0MediaUsername\0\0\0SetMotionConfigURL(QString)\0MotionConfigURL\0\0\0SetMotionDataURL(QString)\0MotionDataURL\0\0\0SetMute(bool)\0Mute\0\0\0SetNetworkTimeout(int)\0NetworkTimeout\0\0"
    "\0SetOneClickZoom(bool)\0OneClickZoom\0\0\0SetPTZControlURL(QString)\0PTZControlURL\0\0\0SetPopups(int)\0Popups\0\0\0SetReconnectionStrategy(int,int,int,int,int,int,bool)\0theDuration1,theConnectionInterval1,theDuration2,theConnectionInterval2,theDuration3,theConnectionInterval3,infiniteMode\0"
    "\0\0SetShowStatusBar(bool)\0ShowStatusBar\0\0\0SetShowToolbar(bool)\0ShowToolbar\0\0\0SetStretchToFit(bool)\0StretchToFit\0\0\0SetSvgDataUrl(QString)\0SvgDataUrl\0\0\0SetToolbarConfiguration(QString)\0ToolbarConfiguration\0"
    "\0\0SetUIMode(QString)\0UIMode\0\0\0SetUserWindow(int,QString,int,int,int,int,int,int,int)\0theID,theName,theXPos,theYPos,theWidth,theHeight,theColor,theOpacity,theFlags\0\0\0SetVolume(int)\0Volume\0\0\0StartRecord(QString)\0"
    "theFile\0\0\0StartRecordMedia(QString,int,QString)\0theFile,theFlags,theMediaTypes\0\0\0StartTransmitMedia(QString,int)\0theFile,theFlags\0\0\0Stop()\0\0\0\0StopRecord()\0\0\0\0StopRecordMedia()\0\0\0\0StopTransmitMedia()\0\0\0"
    "\0TogglePause()\0\0\0\0"
    "AudioConfigURL\0QString\0AudioFile\0QString\0AudioReceiveURL\0QString\0AudioTransmitMute\0bool\0AudioTransmitURL\0QString\0AudioTransmitVolume\0int\0AutoStart\0bool\0ButtonColor\0uint\0ClarifyEnabled\0"
    "bool\0ClarifyLevel\0int\0ClarifyLicenseFile\0QString\0ClarifyValidatorsLocation\0QString\0ClientOverlay\0int\0CurrentPosition\0int\0DisplayMessages\0bool\0Duration\0int\0EnableAreaZoom\0bool\0EnableContextMenu\0bool\0EnableJoystick\0"
    "bool\0EnableReconnect\0bool\0EnableRecording\0int\0FramesDrawn\0int\0FullScreen\0bool\0H264VideoDecodingMode\0int\0H264VideoRenderer\0int\0JoystickConnected\0bool\0MPEG2VideoDecodingMode\0int\0MPEG4VideoDecodingMode\0int\0"
    "MPEG4VideoRenderer\0int\0MediaFile\0QString\0MediaPassword\0QString\0MediaType\0QString\0MediaURL\0QString\0MediaUsername\0QString\0MotionConfigURL\0QString\0MotionDataURL\0QString\0Mute\0bool\0NetworkTimeout\0int\0OneClickZoom\0"
    "bool\0PTZControlURL\0QString\0Popups\0int\0ShowStatusBar\0bool\0ShowToolbar\0bool\0Status\0int\0StretchToFit\0bool\0SvgDataUrl\0QString\0ToolbarConfiguration\0QString\0UIMode\0QString\0Volume\0int\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IAxisMediaControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXISMEDIACONTROLLib__IAxisMediaControl(),
qt_meta_data_AXISMEDIACONTROLLib__IAxisMediaControl }
};

void *IAxisMediaControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXISMEDIACONTROLLib__IAxisMediaControl()))
        return static_cast<void*>(const_cast<IAxisMediaControl*>(this));
    return QAxObject::qt_metacast(_clname);
}

