/****************************************************************************
**
** Namespace AXISMEDIACONTROLLib generated by dumpcpp from type library
** C:\Program Files\Axis Communications\AXIS Media Control Embedded\AxisMediaControlEmb.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_AXISMEDIACONTROLLIB_H
#define QAX_DUMPCPP_AXISMEDIACONTROLLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef AXISMEDIACONTROLLIB_EXPORT
#define AXISMEDIACONTROLLIB_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace AXISMEDIACONTROLLib {


// skipping event interface _IAxisMediaControlEvents

class AXISMEDIACONTROLLIB_EXPORT IAxisMediaControl : public QAxObject
{
public:
    IAxisMediaControl(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property AudioConfigURL

    URL for audio configuration

    */
    inline QString AudioConfigURL() const; //Returns the value of AudioConfigURL
    inline void SetAudioConfigURL(const QString& value); //Sets the value of the AudioConfigURL property

    /*
    Property AudioFile

    Name on audio file to open

    */
    inline QString AudioFile() const; //Returns the value of AudioFile
    inline void SetAudioFile(const QString& value); //Sets the value of the AudioFile property

    /*
    Property AudioReceiveURL

    URL for receiving audio

    */
    inline QString AudioReceiveURL() const; //Returns the value of AudioReceiveURL
    inline void SetAudioReceiveURL(const QString& value); //Sets the value of the AudioReceiveURL property

    /*
    Property AudioTransmitMute

    true if the microphone is muted

    */
    inline bool AudioTransmitMute() const; //Returns the value of AudioTransmitMute
    inline void SetAudioTransmitMute(bool value); //Sets the value of the AudioTransmitMute property

    /*
    Property AudioTransmitURL

    URL for transmitting audio

    */
    inline QString AudioTransmitURL() const; //Returns the value of AudioTransmitURL
    inline void SetAudioTransmitURL(const QString& value); //Sets the value of the AudioTransmitURL property

    /*
    Property AudioTransmitVolume

    the volume level of the microphone (0-100)

    */
    inline int AudioTransmitVolume() const; //Returns the value of AudioTransmitVolume
    inline void SetAudioTransmitVolume(int value); //Sets the value of the AudioTransmitVolume property

    /*
    Property AutoStart

    indicates if the media stream is to be played automatically

    */
    inline bool AutoStart() const; //Returns the value of AutoStart
    inline void SetAutoStart(bool value); //Sets the value of the AutoStart property

    /*
    Property ButtonColor

    property ButtonColor

    */
    inline uint ButtonColor() const; //Returns the value of ButtonColor
    inline void SetButtonColor(uint value); //Sets the value of the ButtonColor property

    /*
    Property ClarifyEnabled

    true if image clarifier is enabled

    */
    inline bool ClarifyEnabled() const; //Returns the value of ClarifyEnabled
    inline void SetClarifyEnabled(bool value); //Sets the value of the ClarifyEnabled property

    /*
    Property ClarifyLevel

    the level of clarifying to apply. Range [0-100]

    */
    inline int ClarifyLevel() const; //Returns the value of ClarifyLevel
    inline void SetClarifyLevel(int value); //Sets the value of the ClarifyLevel property

    /*
    Property ClarifyLicenseFile

    the license file to use to validate that clarify is available

    */
    inline QString ClarifyLicenseFile() const; //Returns the value of ClarifyLicenseFile
    inline void SetClarifyLicenseFile(const QString& value); //Sets the value of the ClarifyLicenseFile property

    /*
    Property ClarifyValidatorsLocation

    the location of the validators to use for verifying that clarify is available

    */
    inline QString ClarifyValidatorsLocation() const; //Returns the value of ClarifyValidatorsLocation
    inline void SetClarifyValidatorsLocation(const QString& value); //Sets the value of the ClarifyValidatorsLocation property

    /*
    Property ClientOverlay

    enables or disables ptz vector

    */
    inline int ClientOverlay() const; //Returns the value of ClientOverlay
    inline void SetClientOverlay(int value); //Sets the value of the ClientOverlay property

    /*
    Property CurrentPosition

    the current position in the media stream

    */
    inline int CurrentPosition() const; //Returns the value of CurrentPosition
    inline void SetCurrentPosition(int value); //Sets the value of the CurrentPosition property

    /*
    Property DisplayMessages

    Display popup messages on error. Default true

    */
    inline bool DisplayMessages() const; //Returns the value of DisplayMessages
    inline void SetDisplayMessages(bool value); //Sets the value of the DisplayMessages property

    /*
    Property Duration

    the total duration of the media stream

    */
    inline int Duration() const; //Returns the value of Duration

    /*
    Property EnableAreaZoom

    enables or disables area zoom

    */
    inline bool EnableAreaZoom() const; //Returns the value of EnableAreaZoom
    inline void SetEnableAreaZoom(bool value); //Sets the value of the EnableAreaZoom property

    /*
    Property EnableContextMenu

    property EnableContextMenu

    */
    inline bool EnableContextMenu() const; //Returns the value of EnableContextMenu
    inline void SetEnableContextMenu(bool value); //Sets the value of the EnableContextMenu property

    /*
    Property EnableJoystick

    enables or disables joystick controlled ptz

    */
    inline bool EnableJoystick() const; //Returns the value of EnableJoystick
    inline void SetEnableJoystick(bool value); //Sets the value of the EnableJoystick property

    /*
    Property EnableReconnect

    property EnableReconnect

    */
    inline bool EnableReconnect() const; //Returns the value of EnableReconnect
    inline void SetEnableReconnect(bool value); //Sets the value of the EnableReconnect property

    /*
    Property EnableRecording

    property EnableRecording

    */
    inline int EnableRecording() const; //Returns the value of EnableRecording
    inline void SetEnableRecording(int value); //Sets the value of the EnableRecording property

    /*
    Property FramesDrawn

    the number of frames drawn since streaming started

    */
    inline int FramesDrawn() const; //Returns the value of FramesDrawn

    /*
    Property FullScreen

    true if the media will be shown in full screen mode

    */
    inline bool FullScreen() const; //Returns the value of FullScreen
    inline void SetFullScreen(bool value); //Sets the value of the FullScreen property

    /*
    Property H264VideoDecodingMode

    the decoding mode for H.264 streams

    */
    inline int H264VideoDecodingMode() const; //Returns the value of H264VideoDecodingMode
    inline void SetH264VideoDecodingMode(int value); //Sets the value of the H264VideoDecodingMode property

    /*
    Property H264VideoRenderer

    property H264VideoRenderer

    */
    inline int H264VideoRenderer() const; //Returns the value of H264VideoRenderer
    inline void SetH264VideoRenderer(int value); //Sets the value of the H264VideoRenderer property

    /*
    Property JoystickConnected

    true if a joystick is connected

    */
    inline bool JoystickConnected() const; //Returns the value of JoystickConnected

    /*
    Property MPEG2VideoDecodingMode

    the decoding mode for MPEG-2 streams

    */
    inline int MPEG2VideoDecodingMode() const; //Returns the value of MPEG2VideoDecodingMode
    inline void SetMPEG2VideoDecodingMode(int value); //Sets the value of the MPEG2VideoDecodingMode property

    /*
    Property MPEG4VideoDecodingMode

    the decoding mode for MPEG-4 streams

    */
    inline int MPEG4VideoDecodingMode() const; //Returns the value of MPEG4VideoDecodingMode
    inline void SetMPEG4VideoDecodingMode(int value); //Sets the value of the MPEG4VideoDecodingMode property

    /*
    Property MPEG4VideoRenderer

    property MPEG4VideoRenderer

    */
    inline int MPEG4VideoRenderer() const; //Returns the value of MPEG4VideoRenderer
    inline void SetMPEG4VideoRenderer(int value); //Sets the value of the MPEG4VideoRenderer property

    /*
    Property MediaFile

    complete path and file name to display

    */
    inline QString MediaFile() const; //Returns the value of MediaFile
    inline void SetMediaFile(const QString& value); //Sets the value of the MediaFile property

    /*
    Property MediaPassword

    password for media stream access

    */
    inline QString MediaPassword() const; //Returns the value of MediaPassword
    inline void SetMediaPassword(const QString& value); //Sets the value of the MediaPassword property

    /*
    Property MediaType

    type of the media stream

    */
    inline QString MediaType() const; //Returns the value of MediaType
    inline void SetMediaType(const QString& value); //Sets the value of the MediaType property

    /*
    Property MediaURL

    URL where the media stream can be accessed

    */
    inline QString MediaURL() const; //Returns the value of MediaURL
    inline void SetMediaURL(const QString& value); //Sets the value of the MediaURL property

    /*
    Property MediaUsername

    username for media stream access

    */
    inline QString MediaUsername() const; //Returns the value of MediaUsername
    inline void SetMediaUsername(const QString& value); //Sets the value of the MediaUsername property

    /*
    Property MotionConfigURL

    URL where Motion Detection windows can be configured

    */
    inline QString MotionConfigURL() const; //Returns the value of MotionConfigURL
    inline void SetMotionConfigURL(const QString& value); //Sets the value of the MotionConfigURL property

    /*
    Property MotionDataURL

    URL where Motion Detection Data can be fetched

    */
    inline QString MotionDataURL() const; //Returns the value of MotionDataURL
    inline void SetMotionDataURL(const QString& value); //Sets the value of the MotionDataURL property

    /*
    Property Mute

    true if the volume is muted

    */
    inline bool Mute() const; //Returns the value of Mute
    inline void SetMute(bool value); //Sets the value of the Mute property

    /*
    Property NetworkTimeout

    the network timeout in ms

    */
    inline int NetworkTimeout() const; //Returns the value of NetworkTimeout
    inline void SetNetworkTimeout(int value); //Sets the value of the NetworkTimeout property

    /*
    Property OneClickZoom

    true if OneClickZoom should be used

    */
    inline bool OneClickZoom() const; //Returns the value of OneClickZoom
    inline void SetOneClickZoom(bool value); //Sets the value of the OneClickZoom property

    /*
    Property PTZControlURL

    the PTZ control URL on the device to access

    */
    inline QString PTZControlURL() const; //Returns the value of PTZControlURL
    inline void SetPTZControlURL(const QString& value); //Sets the value of the PTZControlURL property

    /*
    Property Popups

    Display popup messages and/or Login Dialogs.

    */
    inline int Popups() const; //Returns the value of Popups
    inline void SetPopups(int value); //Sets the value of the Popups property

    /*
    Property ShowStatusBar

    true if the statusbar must be shown

    */
    inline bool ShowStatusBar() const; //Returns the value of ShowStatusBar
    inline void SetShowStatusBar(bool value); //Sets the value of the ShowStatusBar property

    /*
    Property ShowToolbar

    true if the toolbar must be shown

    */
    inline bool ShowToolbar() const; //Returns the value of ShowToolbar
    inline void SetShowToolbar(bool value); //Sets the value of the ShowToolbar property

    /*
    Property Status

    the current status of this component

    */
    inline int Status() const; //Returns the value of Status

    /*
    Property StretchToFit

    true if stretched to fit the control frame size

    */
    inline bool StretchToFit() const; //Returns the value of StretchToFit
    inline void SetStretchToFit(bool value); //Sets the value of the StretchToFit property

    /*
    Property SvgDataUrl

    property SvgDataUrl

    */
    inline QString SvgDataUrl() const; //Returns the value of SvgDataUrl
    inline void SetSvgDataUrl(const QString& value); //Sets the value of the SvgDataUrl property

    /*
    Property ToolbarConfiguration

    configuration of controls to display in the toolbar

    */
    inline QString ToolbarConfiguration() const; //Returns the value of ToolbarConfiguration
    inline void SetToolbarConfiguration(const QString& value); //Sets the value of the ToolbarConfiguration property

    /*
    Property UIMode

    the user interface mode to use

    */
    inline QString UIMode() const; //Returns the value of UIMode
    inline void SetUIMode(const QString& value); //Sets the value of the UIMode property

    /*
    Property Volume

    the volume level of the control (0-100)

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Method AudioReceiveStart

    Starts receiveing audio

    */
    inline void AudioReceiveStart();

    /*
    Method AudioReceiveStop

    Stops receiveing audio

    */
    inline void AudioReceiveStop();

    /*
    Method AudioTransmitStart

    Starts transmitting audio

    */
    inline void AudioTransmitStart();

    /*
    Method AudioTransmitStop

    Stops transmitting audio

    */
    inline void AudioTransmitStop();

    /*
    Method GetCurrentImage

    get the current image

    */
    inline void GetCurrentImage(int theFormat, QVariant& theBuffer, int& theBufferSize);

    /*
    Method GetUserWindow

    Gets the properties of an overlay window

    */
    inline void GetUserWindow(int theID);

    /*
    Method GetVersion

    method GetVersion

    */
    inline void GetVersion(const QString& theClsId, int& major, int& minor, int& build, int& revision);

    /*
    Method GetVersionPart

    method GetVersionPart

    */
    inline int GetVersionPart(const QString& theClsId, int thePartIndex);

    /*
    Method Play

    start playing a media stream

    */
    inline void Play();

    /*
    Method RemoveUserWindow

    Removes an overlay window

    */
    inline void RemoveUserWindow(int theID);

    /*
    Method SaveCurrentImage

    save the current image

    */
    inline void SaveCurrentImage(int theFormat, const QString& theFile);

    /*
    Method SetImage

    method SetImage

    */
    inline void SetImage(QVariant& theImage, int& theSize);

    /*
    Method SetReconnectionStrategy

    Configures the reconnection strategy. Defines reconnection phases with the corresponding connection intervals. Up to three phases are supported.

    */
    inline void SetReconnectionStrategy(int theDuration1, int theConnectionInterval1, int theDuration2, int theConnectionInterval2, int theDuration3, int theConnectionInterval3, bool infiniteMode);

    /*
    Method SetUserWindow

    Creates or changes an overlay window

    */
    inline void SetUserWindow(int theID, const QString& theName, int theXPos, int theYPos, int theWidth, int theHeight, int theColor, int theOpacity, int theFlags);

    /*
    Method StartRecord

    start recording a media stream

    */
    inline void StartRecord(const QString& theFile);

    /*
    Method StartRecordMedia

    Starts recording media to file.

    */
    inline void StartRecordMedia(const QString& theFile, int theFlags, const QString& theMediaTypes);

    /*
    Method StartTransmitMedia

    Starts transmitting a media stream.

    */
    inline void StartTransmitMedia(const QString& theFile, int theFlags);

    /*
    Method Stop

    stop playing a media stream

    */
    inline void Stop();

    /*
    Method StopRecord

    stop recording a media stream

    */
    inline void StopRecord();

    /*
    Method StopRecordMedia

    Stops any ongoing recording.

    */
    inline void StopRecordMedia();

    /*
    Method StopTransmitMedia

    Stops transmitting a media stream.

    */
    inline void StopTransmitMedia();

    /*
    Method TogglePause

    pause or unpause playing of a media stream

    */
    inline void TogglePause();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class AXISMEDIACONTROLLIB_EXPORT AxisMediaControl : public QAxWidget
{
public:
    AxisMediaControl(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl("{de625294-70e6-45ed-b895-cffa13aeb044}");
    }

    AxisMediaControl(IAxisMediaControl *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property AudioConfigURL

    URL for audio configuration

    */
    inline QString AudioConfigURL() const; //Returns the value of AudioConfigURL
    inline void SetAudioConfigURL(const QString& value); //Sets the value of the AudioConfigURL property

    /*
    Property AudioFile

    Name on audio file to open

    */
    inline QString AudioFile() const; //Returns the value of AudioFile
    inline void SetAudioFile(const QString& value); //Sets the value of the AudioFile property

    /*
    Property AudioReceiveURL

    URL for receiving audio

    */
    inline QString AudioReceiveURL() const; //Returns the value of AudioReceiveURL
    inline void SetAudioReceiveURL(const QString& value); //Sets the value of the AudioReceiveURL property

    /*
    Property AudioTransmitMute

    true if the microphone is muted

    */
    inline bool AudioTransmitMute() const; //Returns the value of AudioTransmitMute
    inline void SetAudioTransmitMute(bool value); //Sets the value of the AudioTransmitMute property

    /*
    Property AudioTransmitURL

    URL for transmitting audio

    */
    inline QString AudioTransmitURL() const; //Returns the value of AudioTransmitURL
    inline void SetAudioTransmitURL(const QString& value); //Sets the value of the AudioTransmitURL property

    /*
    Property AudioTransmitVolume

    the volume level of the microphone (0-100)

    */
    inline int AudioTransmitVolume() const; //Returns the value of AudioTransmitVolume
    inline void SetAudioTransmitVolume(int value); //Sets the value of the AudioTransmitVolume property

    /*
    Property AutoStart

    indicates if the media stream is to be played automatically

    */
    inline bool AutoStart() const; //Returns the value of AutoStart
    inline void SetAutoStart(bool value); //Sets the value of the AutoStart property

    /*
    Property ButtonColor

    property ButtonColor

    */
    inline uint ButtonColor() const; //Returns the value of ButtonColor
    inline void SetButtonColor(uint value); //Sets the value of the ButtonColor property

    /*
    Property ClarifyEnabled

    true if image clarifier is enabled

    */
    inline bool ClarifyEnabled() const; //Returns the value of ClarifyEnabled
    inline void SetClarifyEnabled(bool value); //Sets the value of the ClarifyEnabled property

    /*
    Property ClarifyLevel

    the level of clarifying to apply. Range [0-100]

    */
    inline int ClarifyLevel() const; //Returns the value of ClarifyLevel
    inline void SetClarifyLevel(int value); //Sets the value of the ClarifyLevel property

    /*
    Property ClarifyLicenseFile

    the license file to use to validate that clarify is available

    */
    inline QString ClarifyLicenseFile() const; //Returns the value of ClarifyLicenseFile
    inline void SetClarifyLicenseFile(const QString& value); //Sets the value of the ClarifyLicenseFile property

    /*
    Property ClarifyValidatorsLocation

    the location of the validators to use for verifying that clarify is available

    */
    inline QString ClarifyValidatorsLocation() const; //Returns the value of ClarifyValidatorsLocation
    inline void SetClarifyValidatorsLocation(const QString& value); //Sets the value of the ClarifyValidatorsLocation property

    /*
    Property ClientOverlay

    enables or disables ptz vector

    */
    inline int ClientOverlay() const; //Returns the value of ClientOverlay
    inline void SetClientOverlay(int value); //Sets the value of the ClientOverlay property

    /*
    Property CurrentPosition

    the current position in the media stream

    */
    inline int CurrentPosition() const; //Returns the value of CurrentPosition
    inline void SetCurrentPosition(int value); //Sets the value of the CurrentPosition property

    /*
    Property DisplayMessages

    Display popup messages on error. Default true

    */
    inline bool DisplayMessages() const; //Returns the value of DisplayMessages
    inline void SetDisplayMessages(bool value); //Sets the value of the DisplayMessages property

    /*
    Property Duration

    the total duration of the media stream

    */
    inline int Duration() const; //Returns the value of Duration

    /*
    Property EnableAreaZoom

    enables or disables area zoom

    */
    inline bool EnableAreaZoom() const; //Returns the value of EnableAreaZoom
    inline void SetEnableAreaZoom(bool value); //Sets the value of the EnableAreaZoom property

    /*
    Property EnableContextMenu

    property EnableContextMenu

    */
    inline bool EnableContextMenu() const; //Returns the value of EnableContextMenu
    inline void SetEnableContextMenu(bool value); //Sets the value of the EnableContextMenu property

    /*
    Property EnableJoystick

    enables or disables joystick controlled ptz

    */
    inline bool EnableJoystick() const; //Returns the value of EnableJoystick
    inline void SetEnableJoystick(bool value); //Sets the value of the EnableJoystick property

    /*
    Property EnableReconnect

    property EnableReconnect

    */
    inline bool EnableReconnect() const; //Returns the value of EnableReconnect
    inline void SetEnableReconnect(bool value); //Sets the value of the EnableReconnect property

    /*
    Property EnableRecording

    property EnableRecording

    */
    inline int EnableRecording() const; //Returns the value of EnableRecording
    inline void SetEnableRecording(int value); //Sets the value of the EnableRecording property

    /*
    Property FramesDrawn

    the number of frames drawn since streaming started

    */
    inline int FramesDrawn() const; //Returns the value of FramesDrawn

    /*
    Property FullScreen

    true if the media will be shown in full screen mode

    */
    inline bool FullScreen() const; //Returns the value of FullScreen
    inline void SetFullScreen(bool value); //Sets the value of the FullScreen property

    /*
    Property H264VideoDecodingMode

    the decoding mode for H.264 streams

    */
    inline int H264VideoDecodingMode() const; //Returns the value of H264VideoDecodingMode
    inline void SetH264VideoDecodingMode(int value); //Sets the value of the H264VideoDecodingMode property

    /*
    Property H264VideoRenderer

    property H264VideoRenderer

    */
    inline int H264VideoRenderer() const; //Returns the value of H264VideoRenderer
    inline void SetH264VideoRenderer(int value); //Sets the value of the H264VideoRenderer property

    /*
    Property JoystickConnected

    true if a joystick is connected

    */
    inline bool JoystickConnected() const; //Returns the value of JoystickConnected

    /*
    Property MPEG2VideoDecodingMode

    the decoding mode for MPEG-2 streams

    */
    inline int MPEG2VideoDecodingMode() const; //Returns the value of MPEG2VideoDecodingMode
    inline void SetMPEG2VideoDecodingMode(int value); //Sets the value of the MPEG2VideoDecodingMode property

    /*
    Property MPEG4VideoDecodingMode

    the decoding mode for MPEG-4 streams

    */
    inline int MPEG4VideoDecodingMode() const; //Returns the value of MPEG4VideoDecodingMode
    inline void SetMPEG4VideoDecodingMode(int value); //Sets the value of the MPEG4VideoDecodingMode property

    /*
    Property MPEG4VideoRenderer

    property MPEG4VideoRenderer

    */
    inline int MPEG4VideoRenderer() const; //Returns the value of MPEG4VideoRenderer
    inline void SetMPEG4VideoRenderer(int value); //Sets the value of the MPEG4VideoRenderer property

    /*
    Property MediaFile

    complete path and file name to display

    */
    inline QString MediaFile() const; //Returns the value of MediaFile
    inline void SetMediaFile(const QString& value); //Sets the value of the MediaFile property

    /*
    Property MediaPassword

    password for media stream access

    */
    inline QString MediaPassword() const; //Returns the value of MediaPassword
    inline void SetMediaPassword(const QString& value); //Sets the value of the MediaPassword property

    /*
    Property MediaType

    type of the media stream

    */
    inline QString MediaType() const; //Returns the value of MediaType
    inline void SetMediaType(const QString& value); //Sets the value of the MediaType property

    /*
    Property MediaURL

    URL where the media stream can be accessed

    */
    inline QString MediaURL() const; //Returns the value of MediaURL
    inline void SetMediaURL(const QString& value); //Sets the value of the MediaURL property

    /*
    Property MediaUsername

    username for media stream access

    */
    inline QString MediaUsername() const; //Returns the value of MediaUsername
    inline void SetMediaUsername(const QString& value); //Sets the value of the MediaUsername property

    /*
    Property MotionConfigURL

    URL where Motion Detection windows can be configured

    */
    inline QString MotionConfigURL() const; //Returns the value of MotionConfigURL
    inline void SetMotionConfigURL(const QString& value); //Sets the value of the MotionConfigURL property

    /*
    Property MotionDataURL

    URL where Motion Detection Data can be fetched

    */
    inline QString MotionDataURL() const; //Returns the value of MotionDataURL
    inline void SetMotionDataURL(const QString& value); //Sets the value of the MotionDataURL property

    /*
    Property Mute

    true if the volume is muted

    */
    inline bool Mute() const; //Returns the value of Mute
    inline void SetMute(bool value); //Sets the value of the Mute property

    /*
    Property NetworkTimeout

    the network timeout in ms

    */
    inline int NetworkTimeout() const; //Returns the value of NetworkTimeout
    inline void SetNetworkTimeout(int value); //Sets the value of the NetworkTimeout property

    /*
    Property OneClickZoom

    true if OneClickZoom should be used

    */
    inline bool OneClickZoom() const; //Returns the value of OneClickZoom
    inline void SetOneClickZoom(bool value); //Sets the value of the OneClickZoom property

    /*
    Property PTZControlURL

    the PTZ control URL on the device to access

    */
    inline QString PTZControlURL() const; //Returns the value of PTZControlURL
    inline void SetPTZControlURL(const QString& value); //Sets the value of the PTZControlURL property

    /*
    Property Popups

    Display popup messages and/or Login Dialogs.

    */
    inline int Popups() const; //Returns the value of Popups
    inline void SetPopups(int value); //Sets the value of the Popups property

    /*
    Property ShowStatusBar

    true if the statusbar must be shown

    */
    inline bool ShowStatusBar() const; //Returns the value of ShowStatusBar
    inline void SetShowStatusBar(bool value); //Sets the value of the ShowStatusBar property

    /*
    Property ShowToolbar

    true if the toolbar must be shown

    */
    inline bool ShowToolbar() const; //Returns the value of ShowToolbar
    inline void SetShowToolbar(bool value); //Sets the value of the ShowToolbar property

    /*
    Property Status

    the current status of this component

    */
    inline int Status() const; //Returns the value of Status

    /*
    Property StretchToFit

    true if stretched to fit the control frame size

    */
    inline bool StretchToFit() const; //Returns the value of StretchToFit
    inline void SetStretchToFit(bool value); //Sets the value of the StretchToFit property

    /*
    Property SvgDataUrl

    property SvgDataUrl

    */
    inline QString SvgDataUrl() const; //Returns the value of SvgDataUrl
    inline void SetSvgDataUrl(const QString& value); //Sets the value of the SvgDataUrl property

    /*
    Property ToolbarConfiguration

    configuration of controls to display in the toolbar

    */
    inline QString ToolbarConfiguration() const; //Returns the value of ToolbarConfiguration
    inline void SetToolbarConfiguration(const QString& value); //Sets the value of the ToolbarConfiguration property

    /*
    Property UIMode

    the user interface mode to use

    */
    inline QString UIMode() const; //Returns the value of UIMode
    inline void SetUIMode(const QString& value); //Sets the value of the UIMode property

    /*
    Property Volume

    the volume level of the control (0-100)

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Method AudioReceiveStart

    Starts receiveing audio

    */
    inline void AudioReceiveStart();

    /*
    Method AudioReceiveStop

    Stops receiveing audio

    */
    inline void AudioReceiveStop();

    /*
    Method AudioTransmitStart

    Starts transmitting audio

    */
    inline void AudioTransmitStart();

    /*
    Method AudioTransmitStop

    Stops transmitting audio

    */
    inline void AudioTransmitStop();

    /*
    Method GetCurrentImage

    get the current image

    */
    inline void GetCurrentImage(int theFormat, QVariant& theBuffer, int& theBufferSize);

    /*
    Method GetUserWindow

    Gets the properties of an overlay window

    */
    inline void GetUserWindow(int theID);

    /*
    Method GetVersion

    method GetVersion

    */
    inline void GetVersion(const QString& theClsId, int& major, int& minor, int& build, int& revision);

    /*
    Method GetVersionPart

    method GetVersionPart

    */
    inline int GetVersionPart(const QString& theClsId, int thePartIndex);

    /*
    Method Play

    start playing a media stream

    */
    inline void Play();

    /*
    Method RemoveUserWindow

    Removes an overlay window

    */
    inline void RemoveUserWindow(int theID);

    /*
    Method SaveCurrentImage

    save the current image

    */
    inline void SaveCurrentImage(int theFormat, const QString& theFile);

    /*
    Method SetImage

    method SetImage

    */
    inline void SetImage(QVariant& theImage, int& theSize);

    /*
    Method SetReconnectionStrategy

    Configures the reconnection strategy. Defines reconnection phases with the corresponding connection intervals. Up to three phases are supported.

    */
    inline void SetReconnectionStrategy(int theDuration1, int theConnectionInterval1, int theDuration2, int theConnectionInterval2, int theDuration3, int theConnectionInterval3, bool infiniteMode);

    /*
    Method SetUserWindow

    Creates or changes an overlay window

    */
    inline void SetUserWindow(int theID, const QString& theName, int theXPos, int theYPos, int theWidth, int theHeight, int theColor, int theOpacity, int theFlags);

    /*
    Method StartRecord

    start recording a media stream

    */
    inline void StartRecord(const QString& theFile);

    /*
    Method StartRecordMedia

    Starts recording media to file.

    */
    inline void StartRecordMedia(const QString& theFile, int theFlags, const QString& theMediaTypes);

    /*
    Method StartTransmitMedia

    Starts transmitting a media stream.

    */
    inline void StartTransmitMedia(const QString& theFile, int theFlags);

    /*
    Method Stop

    stop playing a media stream

    */
    inline void Stop();

    /*
    Method StopRecord

    stop recording a media stream

    */
    inline void StopRecord();

    /*
    Method StopRecordMedia

    Stops any ongoing recording.

    */
    inline void StopRecordMedia();

    /*
    Method StopTransmitMedia

    Stops transmitting a media stream.

    */
    inline void StopTransmitMedia();

    /*
    Method TogglePause

    pause or unpause playing of a media stream

    */
    inline void TogglePause();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_AXISMEDIACONTROLLIB_NOINLINES
inline QString AxisMediaControl::AudioConfigURL() const
{
    QVariant qax_result = property("AudioConfigURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioConfigURL(const QString& value){ setProperty("AudioConfigURL", QVariant(value)); }

inline QString AxisMediaControl::AudioFile() const
{
    QVariant qax_result = property("AudioFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioFile(const QString& value){ setProperty("AudioFile", QVariant(value)); }

inline QString AxisMediaControl::AudioReceiveURL() const
{
    QVariant qax_result = property("AudioReceiveURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioReceiveURL(const QString& value){ setProperty("AudioReceiveURL", QVariant(value)); }

inline bool AxisMediaControl::AudioTransmitMute() const
{
    QVariant qax_result = property("AudioTransmitMute");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioTransmitMute(bool value){ setProperty("AudioTransmitMute", QVariant(value)); }

inline QString AxisMediaControl::AudioTransmitURL() const
{
    QVariant qax_result = property("AudioTransmitURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioTransmitURL(const QString& value){ setProperty("AudioTransmitURL", QVariant(value)); }

inline int AxisMediaControl::AudioTransmitVolume() const
{
    QVariant qax_result = property("AudioTransmitVolume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetAudioTransmitVolume(int value){ setProperty("AudioTransmitVolume", QVariant(value)); }

inline bool AxisMediaControl::AutoStart() const
{
    QVariant qax_result = property("AutoStart");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetAutoStart(bool value){ setProperty("AutoStart", QVariant(value)); }

inline uint AxisMediaControl::ButtonColor() const
{
    QVariant qax_result = property("ButtonColor");
    Q_ASSERT(qax_result.isValid());
    return *(uint*)qax_result.constData();
}
inline void AxisMediaControl::SetButtonColor(uint value){ setProperty("ButtonColor", QVariant(value)); }

inline bool AxisMediaControl::ClarifyEnabled() const
{
    QVariant qax_result = property("ClarifyEnabled");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetClarifyEnabled(bool value){ setProperty("ClarifyEnabled", QVariant(value)); }

inline int AxisMediaControl::ClarifyLevel() const
{
    QVariant qax_result = property("ClarifyLevel");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetClarifyLevel(int value){ setProperty("ClarifyLevel", QVariant(value)); }

inline QString AxisMediaControl::ClarifyLicenseFile() const
{
    QVariant qax_result = property("ClarifyLicenseFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetClarifyLicenseFile(const QString& value){ setProperty("ClarifyLicenseFile", QVariant(value)); }

inline QString AxisMediaControl::ClarifyValidatorsLocation() const
{
    QVariant qax_result = property("ClarifyValidatorsLocation");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetClarifyValidatorsLocation(const QString& value){ setProperty("ClarifyValidatorsLocation", QVariant(value)); }

inline int AxisMediaControl::ClientOverlay() const
{
    QVariant qax_result = property("ClientOverlay");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetClientOverlay(int value){ setProperty("ClientOverlay", QVariant(value)); }

inline int AxisMediaControl::CurrentPosition() const
{
    QVariant qax_result = property("CurrentPosition");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetCurrentPosition(int value){ setProperty("CurrentPosition", QVariant(value)); }

inline bool AxisMediaControl::DisplayMessages() const
{
    QVariant qax_result = property("DisplayMessages");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetDisplayMessages(bool value){ setProperty("DisplayMessages", QVariant(value)); }

inline int AxisMediaControl::Duration() const
{
    QVariant qax_result = property("Duration");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool AxisMediaControl::EnableAreaZoom() const
{
    QVariant qax_result = property("EnableAreaZoom");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetEnableAreaZoom(bool value){ setProperty("EnableAreaZoom", QVariant(value)); }

inline bool AxisMediaControl::EnableContextMenu() const
{
    QVariant qax_result = property("EnableContextMenu");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetEnableContextMenu(bool value){ setProperty("EnableContextMenu", QVariant(value)); }

inline bool AxisMediaControl::EnableJoystick() const
{
    QVariant qax_result = property("EnableJoystick");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetEnableJoystick(bool value){ setProperty("EnableJoystick", QVariant(value)); }

inline bool AxisMediaControl::EnableReconnect() const
{
    QVariant qax_result = property("EnableReconnect");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetEnableReconnect(bool value){ setProperty("EnableReconnect", QVariant(value)); }

inline int AxisMediaControl::EnableRecording() const
{
    QVariant qax_result = property("EnableRecording");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetEnableRecording(int value){ setProperty("EnableRecording", QVariant(value)); }

inline int AxisMediaControl::FramesDrawn() const
{
    QVariant qax_result = property("FramesDrawn");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool AxisMediaControl::FullScreen() const
{
    QVariant qax_result = property("FullScreen");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetFullScreen(bool value){ setProperty("FullScreen", QVariant(value)); }

inline int AxisMediaControl::H264VideoDecodingMode() const
{
    QVariant qax_result = property("H264VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetH264VideoDecodingMode(int value){ setProperty("H264VideoDecodingMode", QVariant(value)); }

inline int AxisMediaControl::H264VideoRenderer() const
{
    QVariant qax_result = property("H264VideoRenderer");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetH264VideoRenderer(int value){ setProperty("H264VideoRenderer", QVariant(value)); }

inline bool AxisMediaControl::JoystickConnected() const
{
    QVariant qax_result = property("JoystickConnected");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int AxisMediaControl::MPEG2VideoDecodingMode() const
{
    QVariant qax_result = property("MPEG2VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetMPEG2VideoDecodingMode(int value){ setProperty("MPEG2VideoDecodingMode", QVariant(value)); }

inline int AxisMediaControl::MPEG4VideoDecodingMode() const
{
    QVariant qax_result = property("MPEG4VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetMPEG4VideoDecodingMode(int value){ setProperty("MPEG4VideoDecodingMode", QVariant(value)); }

inline int AxisMediaControl::MPEG4VideoRenderer() const
{
    QVariant qax_result = property("MPEG4VideoRenderer");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetMPEG4VideoRenderer(int value){ setProperty("MPEG4VideoRenderer", QVariant(value)); }

inline QString AxisMediaControl::MediaFile() const
{
    QVariant qax_result = property("MediaFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMediaFile(const QString& value){ setProperty("MediaFile", QVariant(value)); }

inline QString AxisMediaControl::MediaPassword() const
{
    QVariant qax_result = property("MediaPassword");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMediaPassword(const QString& value){ setProperty("MediaPassword", QVariant(value)); }

inline QString AxisMediaControl::MediaType() const
{
    QVariant qax_result = property("MediaType");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMediaType(const QString& value){ setProperty("MediaType", QVariant(value)); }

inline QString AxisMediaControl::MediaURL() const
{
    QVariant qax_result = property("MediaURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMediaURL(const QString& value){ setProperty("MediaURL", QVariant(value)); }

inline QString AxisMediaControl::MediaUsername() const
{
    QVariant qax_result = property("MediaUsername");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMediaUsername(const QString& value){ setProperty("MediaUsername", QVariant(value)); }

inline QString AxisMediaControl::MotionConfigURL() const
{
    QVariant qax_result = property("MotionConfigURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMotionConfigURL(const QString& value){ setProperty("MotionConfigURL", QVariant(value)); }

inline QString AxisMediaControl::MotionDataURL() const
{
    QVariant qax_result = property("MotionDataURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetMotionDataURL(const QString& value){ setProperty("MotionDataURL", QVariant(value)); }

inline bool AxisMediaControl::Mute() const
{
    QVariant qax_result = property("Mute");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetMute(bool value){ setProperty("Mute", QVariant(value)); }

inline int AxisMediaControl::NetworkTimeout() const
{
    QVariant qax_result = property("NetworkTimeout");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetNetworkTimeout(int value){ setProperty("NetworkTimeout", QVariant(value)); }

inline bool AxisMediaControl::OneClickZoom() const
{
    QVariant qax_result = property("OneClickZoom");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetOneClickZoom(bool value){ setProperty("OneClickZoom", QVariant(value)); }

inline QString AxisMediaControl::PTZControlURL() const
{
    QVariant qax_result = property("PTZControlURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetPTZControlURL(const QString& value){ setProperty("PTZControlURL", QVariant(value)); }

inline int AxisMediaControl::Popups() const
{
    QVariant qax_result = property("Popups");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetPopups(int value){ setProperty("Popups", QVariant(value)); }

inline bool AxisMediaControl::ShowStatusBar() const
{
    QVariant qax_result = property("ShowStatusBar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetShowStatusBar(bool value){ setProperty("ShowStatusBar", QVariant(value)); }

inline bool AxisMediaControl::ShowToolbar() const
{
    QVariant qax_result = property("ShowToolbar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetShowToolbar(bool value){ setProperty("ShowToolbar", QVariant(value)); }

inline int AxisMediaControl::Status() const
{
    QVariant qax_result = property("Status");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool AxisMediaControl::StretchToFit() const
{
    QVariant qax_result = property("StretchToFit");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void AxisMediaControl::SetStretchToFit(bool value){ setProperty("StretchToFit", QVariant(value)); }

inline QString AxisMediaControl::SvgDataUrl() const
{
    QVariant qax_result = property("SvgDataUrl");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetSvgDataUrl(const QString& value){ setProperty("SvgDataUrl", QVariant(value)); }

inline QString AxisMediaControl::ToolbarConfiguration() const
{
    QVariant qax_result = property("ToolbarConfiguration");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetToolbarConfiguration(const QString& value){ setProperty("ToolbarConfiguration", QVariant(value)); }

inline QString AxisMediaControl::UIMode() const
{
    QVariant qax_result = property("UIMode");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void AxisMediaControl::SetUIMode(const QString& value){ setProperty("UIMode", QVariant(value)); }

inline int AxisMediaControl::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void AxisMediaControl::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline void AxisMediaControl::AudioReceiveStart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
}

inline void AxisMediaControl::AudioReceiveStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void AxisMediaControl::AudioTransmitStart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void AxisMediaControl::AudioTransmitStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
}

inline void AxisMediaControl::GetCurrentImage(int theFormat, QVariant& theBuffer, int& theBufferSize)
{
    void *_a[] = {0, (void*)&theFormat, (void*)&theBuffer, (void*)&theBufferSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void AxisMediaControl::GetUserWindow(int theID)
{
    void *_a[] = {0, (void*)&theID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}

inline void AxisMediaControl::GetVersion(const QString& theClsId, int& major, int& minor, int& build, int& revision)
{
    void *_a[] = {0, (void*)&theClsId, (void*)&major, (void*)&minor, (void*)&build, (void*)&revision};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
}

inline int AxisMediaControl::GetVersionPart(const QString& theClsId, int thePartIndex)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&theClsId, (void*)&thePartIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
    return qax_result;
}

inline void AxisMediaControl::Play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
}

inline void AxisMediaControl::RemoveUserWindow(int theID)
{
    void *_a[] = {0, (void*)&theID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
}

inline void AxisMediaControl::SaveCurrentImage(int theFormat, const QString& theFile)
{
    void *_a[] = {0, (void*)&theFormat, (void*)&theFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
}

inline void AxisMediaControl::SetImage(QVariant& theImage, int& theSize)
{
    void *_a[] = {0, (void*)&theImage, (void*)&theSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
}

inline void AxisMediaControl::SetReconnectionStrategy(int theDuration1, int theConnectionInterval1, int theDuration2, int theConnectionInterval2, int theDuration3, int theConnectionInterval3, bool infiniteMode)
{
    void *_a[] = {0, (void*)&theDuration1, (void*)&theConnectionInterval1, (void*)&theDuration2, (void*)&theConnectionInterval2, (void*)&theDuration3, (void*)&theConnectionInterval3, (void*)&infiniteMode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 92, _a);
}

inline void AxisMediaControl::SetUserWindow(int theID, const QString& theName, int theXPos, int theYPos, int theWidth, int theHeight, int theColor, int theOpacity, int theFlags)
{
    void *_a[] = {0, (void*)&theID, (void*)&theName, (void*)&theXPos, (void*)&theYPos, (void*)&theWidth, (void*)&theHeight, (void*)&theColor, (void*)&theOpacity, (void*)&theFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 99, _a);
}

inline void AxisMediaControl::StartRecord(const QString& theFile)
{
    void *_a[] = {0, (void*)&theFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 101, _a);
}

inline void AxisMediaControl::StartRecordMedia(const QString& theFile, int theFlags, const QString& theMediaTypes)
{
    void *_a[] = {0, (void*)&theFile, (void*)&theFlags, (void*)&theMediaTypes};
    qt_metacall(QMetaObject::InvokeMetaMethod, 102, _a);
}

inline void AxisMediaControl::StartTransmitMedia(const QString& theFile, int theFlags)
{
    void *_a[] = {0, (void*)&theFile, (void*)&theFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 103, _a);
}

inline void AxisMediaControl::Stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 104, _a);
}

inline void AxisMediaControl::StopRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 105, _a);
}

inline void AxisMediaControl::StopRecordMedia()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 106, _a);
}

inline void AxisMediaControl::StopTransmitMedia()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 107, _a);
}

inline void AxisMediaControl::TogglePause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 108, _a);
}


inline QString IAxisMediaControl::AudioConfigURL() const
{
    QVariant qax_result = property("AudioConfigURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioConfigURL(const QString& value){ setProperty("AudioConfigURL", QVariant(value)); }

inline QString IAxisMediaControl::AudioFile() const
{
    QVariant qax_result = property("AudioFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioFile(const QString& value){ setProperty("AudioFile", QVariant(value)); }

inline QString IAxisMediaControl::AudioReceiveURL() const
{
    QVariant qax_result = property("AudioReceiveURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioReceiveURL(const QString& value){ setProperty("AudioReceiveURL", QVariant(value)); }

inline bool IAxisMediaControl::AudioTransmitMute() const
{
    QVariant qax_result = property("AudioTransmitMute");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioTransmitMute(bool value){ setProperty("AudioTransmitMute", QVariant(value)); }

inline QString IAxisMediaControl::AudioTransmitURL() const
{
    QVariant qax_result = property("AudioTransmitURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioTransmitURL(const QString& value){ setProperty("AudioTransmitURL", QVariant(value)); }

inline int IAxisMediaControl::AudioTransmitVolume() const
{
    QVariant qax_result = property("AudioTransmitVolume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetAudioTransmitVolume(int value){ setProperty("AudioTransmitVolume", QVariant(value)); }

inline bool IAxisMediaControl::AutoStart() const
{
    QVariant qax_result = property("AutoStart");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetAutoStart(bool value){ setProperty("AutoStart", QVariant(value)); }

inline uint IAxisMediaControl::ButtonColor() const
{
    QVariant qax_result = property("ButtonColor");
    Q_ASSERT(qax_result.isValid());
    return *(uint*)qax_result.constData();
}
inline void IAxisMediaControl::SetButtonColor(uint value){ setProperty("ButtonColor", QVariant(value)); }

inline bool IAxisMediaControl::ClarifyEnabled() const
{
    QVariant qax_result = property("ClarifyEnabled");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetClarifyEnabled(bool value){ setProperty("ClarifyEnabled", QVariant(value)); }

inline int IAxisMediaControl::ClarifyLevel() const
{
    QVariant qax_result = property("ClarifyLevel");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetClarifyLevel(int value){ setProperty("ClarifyLevel", QVariant(value)); }

inline QString IAxisMediaControl::ClarifyLicenseFile() const
{
    QVariant qax_result = property("ClarifyLicenseFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetClarifyLicenseFile(const QString& value){ setProperty("ClarifyLicenseFile", QVariant(value)); }

inline QString IAxisMediaControl::ClarifyValidatorsLocation() const
{
    QVariant qax_result = property("ClarifyValidatorsLocation");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetClarifyValidatorsLocation(const QString& value){ setProperty("ClarifyValidatorsLocation", QVariant(value)); }

inline int IAxisMediaControl::ClientOverlay() const
{
    QVariant qax_result = property("ClientOverlay");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetClientOverlay(int value){ setProperty("ClientOverlay", QVariant(value)); }

inline int IAxisMediaControl::CurrentPosition() const
{
    QVariant qax_result = property("CurrentPosition");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetCurrentPosition(int value){ setProperty("CurrentPosition", QVariant(value)); }

inline bool IAxisMediaControl::DisplayMessages() const
{
    QVariant qax_result = property("DisplayMessages");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetDisplayMessages(bool value){ setProperty("DisplayMessages", QVariant(value)); }

inline int IAxisMediaControl::Duration() const
{
    QVariant qax_result = property("Duration");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool IAxisMediaControl::EnableAreaZoom() const
{
    QVariant qax_result = property("EnableAreaZoom");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetEnableAreaZoom(bool value){ setProperty("EnableAreaZoom", QVariant(value)); }

inline bool IAxisMediaControl::EnableContextMenu() const
{
    QVariant qax_result = property("EnableContextMenu");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetEnableContextMenu(bool value){ setProperty("EnableContextMenu", QVariant(value)); }

inline bool IAxisMediaControl::EnableJoystick() const
{
    QVariant qax_result = property("EnableJoystick");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetEnableJoystick(bool value){ setProperty("EnableJoystick", QVariant(value)); }

inline bool IAxisMediaControl::EnableReconnect() const
{
    QVariant qax_result = property("EnableReconnect");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetEnableReconnect(bool value){ setProperty("EnableReconnect", QVariant(value)); }

inline int IAxisMediaControl::EnableRecording() const
{
    QVariant qax_result = property("EnableRecording");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetEnableRecording(int value){ setProperty("EnableRecording", QVariant(value)); }

inline int IAxisMediaControl::FramesDrawn() const
{
    QVariant qax_result = property("FramesDrawn");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool IAxisMediaControl::FullScreen() const
{
    QVariant qax_result = property("FullScreen");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetFullScreen(bool value){ setProperty("FullScreen", QVariant(value)); }

inline int IAxisMediaControl::H264VideoDecodingMode() const
{
    QVariant qax_result = property("H264VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetH264VideoDecodingMode(int value){ setProperty("H264VideoDecodingMode", QVariant(value)); }

inline int IAxisMediaControl::H264VideoRenderer() const
{
    QVariant qax_result = property("H264VideoRenderer");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetH264VideoRenderer(int value){ setProperty("H264VideoRenderer", QVariant(value)); }

inline bool IAxisMediaControl::JoystickConnected() const
{
    QVariant qax_result = property("JoystickConnected");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int IAxisMediaControl::MPEG2VideoDecodingMode() const
{
    QVariant qax_result = property("MPEG2VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetMPEG2VideoDecodingMode(int value){ setProperty("MPEG2VideoDecodingMode", QVariant(value)); }

inline int IAxisMediaControl::MPEG4VideoDecodingMode() const
{
    QVariant qax_result = property("MPEG4VideoDecodingMode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetMPEG4VideoDecodingMode(int value){ setProperty("MPEG4VideoDecodingMode", QVariant(value)); }

inline int IAxisMediaControl::MPEG4VideoRenderer() const
{
    QVariant qax_result = property("MPEG4VideoRenderer");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetMPEG4VideoRenderer(int value){ setProperty("MPEG4VideoRenderer", QVariant(value)); }

inline QString IAxisMediaControl::MediaFile() const
{
    QVariant qax_result = property("MediaFile");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMediaFile(const QString& value){ setProperty("MediaFile", QVariant(value)); }

inline QString IAxisMediaControl::MediaPassword() const
{
    QVariant qax_result = property("MediaPassword");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMediaPassword(const QString& value){ setProperty("MediaPassword", QVariant(value)); }

inline QString IAxisMediaControl::MediaType() const
{
    QVariant qax_result = property("MediaType");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMediaType(const QString& value){ setProperty("MediaType", QVariant(value)); }

inline QString IAxisMediaControl::MediaURL() const
{
    QVariant qax_result = property("MediaURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMediaURL(const QString& value){ setProperty("MediaURL", QVariant(value)); }

inline QString IAxisMediaControl::MediaUsername() const
{
    QVariant qax_result = property("MediaUsername");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMediaUsername(const QString& value){ setProperty("MediaUsername", QVariant(value)); }

inline QString IAxisMediaControl::MotionConfigURL() const
{
    QVariant qax_result = property("MotionConfigURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMotionConfigURL(const QString& value){ setProperty("MotionConfigURL", QVariant(value)); }

inline QString IAxisMediaControl::MotionDataURL() const
{
    QVariant qax_result = property("MotionDataURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetMotionDataURL(const QString& value){ setProperty("MotionDataURL", QVariant(value)); }

inline bool IAxisMediaControl::Mute() const
{
    QVariant qax_result = property("Mute");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetMute(bool value){ setProperty("Mute", QVariant(value)); }

inline int IAxisMediaControl::NetworkTimeout() const
{
    QVariant qax_result = property("NetworkTimeout");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetNetworkTimeout(int value){ setProperty("NetworkTimeout", QVariant(value)); }

inline bool IAxisMediaControl::OneClickZoom() const
{
    QVariant qax_result = property("OneClickZoom");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetOneClickZoom(bool value){ setProperty("OneClickZoom", QVariant(value)); }

inline QString IAxisMediaControl::PTZControlURL() const
{
    QVariant qax_result = property("PTZControlURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetPTZControlURL(const QString& value){ setProperty("PTZControlURL", QVariant(value)); }

inline int IAxisMediaControl::Popups() const
{
    QVariant qax_result = property("Popups");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetPopups(int value){ setProperty("Popups", QVariant(value)); }

inline bool IAxisMediaControl::ShowStatusBar() const
{
    QVariant qax_result = property("ShowStatusBar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetShowStatusBar(bool value){ setProperty("ShowStatusBar", QVariant(value)); }

inline bool IAxisMediaControl::ShowToolbar() const
{
    QVariant qax_result = property("ShowToolbar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetShowToolbar(bool value){ setProperty("ShowToolbar", QVariant(value)); }

inline int IAxisMediaControl::Status() const
{
    QVariant qax_result = property("Status");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline bool IAxisMediaControl::StretchToFit() const
{
    QVariant qax_result = property("StretchToFit");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IAxisMediaControl::SetStretchToFit(bool value){ setProperty("StretchToFit", QVariant(value)); }

inline QString IAxisMediaControl::SvgDataUrl() const
{
    QVariant qax_result = property("SvgDataUrl");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetSvgDataUrl(const QString& value){ setProperty("SvgDataUrl", QVariant(value)); }

inline QString IAxisMediaControl::ToolbarConfiguration() const
{
    QVariant qax_result = property("ToolbarConfiguration");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetToolbarConfiguration(const QString& value){ setProperty("ToolbarConfiguration", QVariant(value)); }

inline QString IAxisMediaControl::UIMode() const
{
    QVariant qax_result = property("UIMode");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IAxisMediaControl::SetUIMode(const QString& value){ setProperty("UIMode", QVariant(value)); }

inline int IAxisMediaControl::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IAxisMediaControl::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline void IAxisMediaControl::AudioReceiveStart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
}

inline void IAxisMediaControl::AudioReceiveStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void IAxisMediaControl::AudioTransmitStart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void IAxisMediaControl::AudioTransmitStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void IAxisMediaControl::GetCurrentImage(int theFormat, QVariant& theBuffer, int& theBufferSize)
{
    void *_a[] = {0, (void*)&theFormat, (void*)&theBuffer, (void*)&theBufferSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void IAxisMediaControl::GetUserWindow(int theID)
{
    void *_a[] = {0, (void*)&theID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void IAxisMediaControl::GetVersion(const QString& theClsId, int& major, int& minor, int& build, int& revision)
{
    void *_a[] = {0, (void*)&theClsId, (void*)&major, (void*)&minor, (void*)&build, (void*)&revision};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline int IAxisMediaControl::GetVersionPart(const QString& theClsId, int thePartIndex)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&theClsId, (void*)&thePartIndex};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline void IAxisMediaControl::Play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void IAxisMediaControl::RemoveUserWindow(int theID)
{
    void *_a[] = {0, (void*)&theID};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void IAxisMediaControl::SaveCurrentImage(int theFormat, const QString& theFile)
{
    void *_a[] = {0, (void*)&theFormat, (void*)&theFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}

inline void IAxisMediaControl::SetImage(QVariant& theImage, int& theSize)
{
    void *_a[] = {0, (void*)&theImage, (void*)&theSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
}

inline void IAxisMediaControl::SetReconnectionStrategy(int theDuration1, int theConnectionInterval1, int theDuration2, int theConnectionInterval2, int theDuration3, int theConnectionInterval3, bool infiniteMode)
{
    void *_a[] = {0, (void*)&theDuration1, (void*)&theConnectionInterval1, (void*)&theDuration2, (void*)&theConnectionInterval2, (void*)&theDuration3, (void*)&theConnectionInterval3, (void*)&infiniteMode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
}

inline void IAxisMediaControl::SetUserWindow(int theID, const QString& theName, int theXPos, int theYPos, int theWidth, int theHeight, int theColor, int theOpacity, int theFlags)
{
    void *_a[] = {0, (void*)&theID, (void*)&theName, (void*)&theXPos, (void*)&theYPos, (void*)&theWidth, (void*)&theHeight, (void*)&theColor, (void*)&theOpacity, (void*)&theFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
}

inline void IAxisMediaControl::StartRecord(const QString& theFile)
{
    void *_a[] = {0, (void*)&theFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
}

inline void IAxisMediaControl::StartRecordMedia(const QString& theFile, int theFlags, const QString& theMediaTypes)
{
    void *_a[] = {0, (void*)&theFile, (void*)&theFlags, (void*)&theMediaTypes};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
}

inline void IAxisMediaControl::StartTransmitMedia(const QString& theFile, int theFlags)
{
    void *_a[] = {0, (void*)&theFile, (void*)&theFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
}

inline void IAxisMediaControl::Stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
}

inline void IAxisMediaControl::StopRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
}

inline void IAxisMediaControl::StopRecordMedia()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
}

inline void IAxisMediaControl::StopTransmitMedia()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
}

inline void IAxisMediaControl::TogglePause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
}



#endif

}

template<>
inline void *qMetaTypeConstructHelper(const AXISMEDIACONTROLLib::AxisMediaControl *t)
{ Q_ASSERT(!t); return new AXISMEDIACONTROLLib::AxisMediaControl; }

template<>
inline void *qMetaTypeConstructHelper(const AXISMEDIACONTROLLib::IAxisMediaControl *t)
{ Q_ASSERT(!t); return new AXISMEDIACONTROLLib::IAxisMediaControl; }

#endif

