<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets"/>
  <PropertyGroup Label="UserMacros"/>
  <PropertyGroup/>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>
        "includes";
        "..\..\includes";
        "l:\commun_nt\cmdl\10.0.0";
        "l:\commun_nt\declare\10.0.0";
        "l:\ls_nt\oci\11.2.0.1.0_64bit\include";
      </AdditionalIncludeDirectories>
      <PreprocessorDefinitions>
        "DBIF_ORA11";
        "DBIF_ORAVER=11";
      </PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>



